% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{book}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage[]{natbib}
\bibliographystyle{plainnat}
\usepackage{booktabs}

\AtBeginEnvironment{verbatim}{\small}
\AtEndEnvironment{verbatim}{}

\usepackage[estonian, provide=*]{babel}
\usepackage{float}

\usepackage{CormorantGaramond}
%\usepackage{ebgaramond-maths}
%\usepackage{times}

\usepackage{makeidx}


\usepackage[top=25mm,
   bottom=25mm,
   inner=25mm,
   outer=20mm]{geometry}

\usepackage[labelsep=period,small,singlelinecheck=false]{caption}

\usepackage{fancyhdr}

\setlength{\headheight}{15pt}
\fancypagestyle{plain}{%
	\fancyhf{} % eemalda kõik päised ja jalused
	\renewcommand{\headrulewidth}{0pt} % eemalda joon päise all
	\fancyfoot[C]{\thepage} % ainult lehekülje number
}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[LE,RO]{\thepage}
\fancyhead[RE]{\leftmark}
\fancyhead[LO]{\rightmark}

   
% Kaane kujunduse määratlus
\usepackage{graphicx} % Vajalik piltide lisamiseks
\usepackage[absolute,overlay]{textpos} % Teksti paigutamiseks pildi peale
\usepackage{xcolor} % Värvi kasutamiseks

\newcommand{\naitefont}{\usefont{T1}{cmbr}{m}{n}\fontsize{8}{14}\selectfont}

\newcounter{naidis}[chapter]

\newenvironment{naidis}
{%
\definecolor{shadecolor}{rgb}{200, 200, 0}
\par\parindent 0pt
\begin{framed}
\begin{naitefont}
\refstepcounter{naidis}\textbf{Näide \thenaidis.}
}
{%
\end{naitefont}%
\end{framed}
}%

\counterwithin{naidis}{chapter}

\DefineVerbatimEnvironment{naideExcel}{Verbatim}{
	xleftmargin=.5cm,
	fontsize=\small,
	formatcom=\color{blue},
	baselinestretch=0.9,
	fontfamily=cmtt
}


\renewcommand{\normalsize}{\fontsize{12}{18}\selectfont}

%\RecustomVerbatimEnvironment{Highlighting}{Verbatim}{fontsize=\small}
\renewenvironment{Shaded} {\begin{snugshade}\footnotesize} {\end{snugshade}}
% Kaane lehe määratlus
\newcommand{\kaanekaas}{
    \begin{titlepage} % Alustab kaane lehte
    \begin{center}
        \vspace*{5cm} % Lisab vertikaalset ruumi

        % Raamatu pealkiri
        {\Huge\bfseries Metsanduslik statistika }\\
        \vspace{0.5cm}
        
        % Alapealkiri
        {\Large R ja MS Excel keskkonnas}\\
        \vspace{3cm}
        
        % Autor
        {\Large\textit{Allan Sims}}\\
        \vspace{0.5cm}
        {\Large\textit{Andres Kiviste}}\\
        \vspace{0.5cm}
        {\Large\textit{Diana Laarmann}}\\
        \vspace{1cm}

        \vfill
        
        % Kirjastuse või muu asjakohase info lisamine
        {\large 2025}
        
    \end{center}
    \end{titlepage}
}

% Kaane lehe lisamine dokumenti enne sisu algust
%\AtBeginDocument{\kaanekaas}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Metsanduslik statistika R ja MS Excel keskkonnas},
  pdfauthor={Allan Sims, Andres Kiviste, Diana Laarmann},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Metsanduslik statistika R ja MS Excel keskkonnas}
\author{Allan Sims, Andres Kiviste, Diana Laarmann}
\date{31.01.2025}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\chapter{Sissejuhatus}\label{sissejuhatus}

Käesolev õpik on mõeldud metsandusüliõpilastele, kes soovivad omandada matemaatilise statistika põhitõdesid praktilises kontekstis. Materjali koostamisel on lähtutud eeldusest, et lugejatel ei pruugi olla sügavamat matemaatilist ettevalmistust. Terminoloogia on kooskõlas \emph{\href{https://sonaveeb.ee/ds/aso}{andmeanalüüsi ja statistika oskussõnastikuga}}, kuid mõisted on lahtiseletatud metsandusvaldkonnast lähtuvalt.

Metsanduses toimub pidev andmete kogumine ja nende töötlemine. Kõiki soovitud andmeid ei ole võimalik alati mõõta ning seetõttu tuletatakse need erinevate mudelite abil. Sellised mudelid on saadud statistilise andmetöötluse ja modelleerimise abil. Seetõttu on andmete töötlemisel oluline tunda ka statistika põhitõdesid, et mõista paremini andmetest järelduste ja otsuste tegemisel. Õpiku näited keskenduvad metsanduslikele andmetele. Tarkvarana on kasutatud statistikatarkvara \textbf{R} ja \textbf{MS Excel}, kuid nende valikul on oluline märkida nende erinevaid võimekusi:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{R} on spetsialiseerunud statistiliseks modelleerimiseks ja analüüsiks, pakkudes laia valikut meetodeid (nt regressioon, testid). Kuid andmehalduse lihtsustamiseks võib olla vaja täiendavaid tööriistu.\\
\item
  \textbf{MS Excel} on kasutajasõbralik platvorm andmete korrastamiseks ja esmaseks visualiseerimiseks, kuid selle statistilised funktsioonid on piiratud (nt puuduvad keerukama modelleerimise võimalused).
\end{enumerate}

Need tarkvarad täiendavad üksteist. MS Excel sobib hästi andmete esmaseks töötluseks, R aga detailsemaks analüüsiks. Näiteks võib MS Excelis ette valmistatud andmeid edasi analüüsida R-is. Samuti on võimalik integreerida R-skripte Exceli makrotesse või kasutada Pythoni skripte R-i keskkonnas, et laiendada funktsionaalsust, aga neid integratsioone käesolev õpik ei käsitle. Sellised moodulipõhised lahendused muudavad tarkvaravahendid paindlikumaks, kuid nõuavad aga pidevat oskuste arendamist.

Oluline on mõista, et üksik tarkvara ei suuda katta kõiki analüüsivajadusi. Seetõttu on õpikus rõhk praktilistel lahendustel, mis õpetavad ülesannete jaoks optimaalsete tööriistade valikut. Statistika valdkond areneb kiiresti -- nii meetodid, tarkvarad kui rakendusvaldkonnad muutuvad. Käesolevat õpikut uuendatakse regulaarselt, et kajastada ajakohaseid standardeid ja tarkvarauuendusi.

\section{Statistikaprogramm R}\label{statistikaprogramm-r}

R on tarkvarakeskkond, mis on loodud spetsiaalselt statistiliseks arvutamiseks ja andmete graafiliseks esitamiseks. See on avatud lähtekoodiga projekt, mida toetab suur kogukond ning mida eelistavad andmeteadlased ja statistikud üle kogu maailma oma andmeanalüüsi vajadusteks. R pakub laia valikut tööriistu andmete importimiseks, töötlemiseks, modelleerimiseks, analüüsiks ja visualiseerimiseks. Järgnevalt on ülevaade R-i peamistest kasutusvõimalustest statistilise analüüsi tegemiseks.

\textbf{Andmete importimine ja töötlemine}

\begin{itemize}
\tightlist
\item
  \textbf{Andmete importimine.} R toetab andmete importimist paljudest allikatest, sealhulgas teksti-, CSV- ja MS Exceli failidest ning andmebaasidest ja isegi veebist.
\item
  \textbf{Andmete puhastamine.} Andmete analüüsiks ettevalmistamisel pakub R võimalusi nende sortimiseks, filtreerimiseks, puuduvate väärtuste käsitlemiseks ja duplikaatide eemaldamiseks.
\end{itemize}

\textbf{Andmete analüüs}

\begin{itemize}
\tightlist
\item
  \textbf{Statistilised funktsioonid.} R sisaldab ulatuslikku valikut sisseehitatud funktsioone statistilisi tunnuste arvutamiseks, nagu keskmine, mediaan, standardhälve, kvantiilid ja palju muud, mis võimaldavad kiiresti arvutada olulisi statistilisi näitajaid.
\item
  \textbf{Andmete manipuleerimine.} R pakub võimekaid pakette andmete manipuleerimiseks, mis võimaldavad efektiivselt andmete filtreerimist, valimist, rühmitamist ja kokkuvõtete tegemist.
\end{itemize}

\textbf{Statistilised mudelid ja analüüsimeetodid}

\begin{itemize}
\tightlist
\item
  \textbf{Hüpoteeside testimine.} R võimaldab kasutajatel teostada erinevaid statistilisi teste, nagu t-testid, hii-ruut-testid, ANOVA ja palju muud, et uurida andmete omavahelisi seoseid ja testida hüpoteese.
\item
  \textbf{Regressioon ja korrelatsioon.} R toetab mitmesuguseid regressioonianalüüse võimaldades seeläbi uurida muutujate vahelisi seoseid.
\end{itemize}

\textbf{Andmete visualiseerimine}

\begin{itemize}
\tightlist
\item
  \textbf{Graafikud ja diagrammid.} R pakub mitmeid pakette andmete visualiseerimiseks võimaldades luua keerukaid ja esteetiliselt meeldivaid graafikuid.
\item
  \textbf{Interaktiivsed visualisatsioonid.} Lisaks staatilistele graafikutele võimaldab R luua interaktiivseid visualisatsioone.
\end{itemize}

\textbf{Laiendatavus ja kogukond}

\begin{itemize}
\tightlist
\item
  \textbf{Pakettide ökosüsteem.} R toetab laialdast pakettide ökosüsteemi, mis katab spetsiifilisi statistilisi meetodeid, andmete visualiseerimise tehnikaid, masinõpet ja palju muud, võimaldades kasutajatel laiendada R-i funktsionaalsust vastavalt vajadusele.
\item
  \textbf{Tugev kogukond.} R-i kasutajate ja arendajate kogukond on väga aktiivne, pakkudes tuge, juhendeid ja ressursse, mis aitavad lahendada keerulisi analüütilisi väljakutseid.
\item
  \textbf{Õpikud ja juhendid.} R-i kasutamiseks on koostatud erinevaid õpikud, mis on mõeldud nii algajatele kui ka edasijõudnutele. Veebilehel \url{https://bookdown.org/} on mitmed sellised õpikud.
\end{itemize}

\subsection{R-i paketid}\label{r-i-paketid}

Statistikaprogramm põhineb pakettidel. Iga pakett on meetodite ja funktsioonide kogumik ning need võimaldavad teha kindlaid protseduure. Kasutajal on võimalik installeerida teiste poolt koostatud pakette või neid vajadusel ise koostada. R-i paketid on tööriistade, funktsioonide ja andmete kogumikud, mis laiendavad R-i põhifunktsionaalsust ning võimaldavad lahendada erinevaid andmetöötluse, statistilise analüüsi ja visualiseerimise ülesandeid. Enamik pakette on loodud R-i kogukonna liikmete poolt. CRAN (Comprehensive R Archive Network) on ametlik hoidla, kuhu arendajad saavad pakette üles laadida ning kasutajad neid alla laadida.

Pakettide installeerimiseks kasutatakse funktsiooni \texttt{install.packages()}. Näiteks:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Kui pakett on installitud, tuleb see sessioonis laadida, kasutades funktsiooni \texttt{library()}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2) }
\CommentTok{\# või}
\FunctionTok{library}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Pakettide puhul tuleb jälgida, et installimise funktsioonis peab paketi nimetus olema jutumärkide vahel, aga paketi sisse laadimisel võib see olla ka jutumärkideta.

Lisaks on ka funktsioon \texttt{require()}, mis võimaldab testida paketi olemasolu. Selline testimise vajadus tekib, kui skripti kasutatakse korduvalt erinevates arvutites ning ühes arvutis skripti loomisel võib olla vajalikud paketid juba installitud ning teises arvutis ei pruugi veel vajalikke pakette olla. Näiteks, kontrollime, kas antud pakett on olemas ning kui see puudub, siis installime:

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{require}\NormalTok{(ggplot2))\{}
    \FunctionTok{install.packages}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)    }
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Funktsioon \texttt{require()} loeb ka paketi sisse, kui see on installitud, aga seda on soovituslik kasutada pigem selleks, et kontrollida paketi olemasolu. Kui koostatud on arvutusskript, milles antud funktsiooniga laaditakse pakett, mis puudub, siis skripti töö jätkub, aga see ebaõnnestub, sest vajalikku paketti ei ole.

Igal paketil on põhjalik dokumentatsioon, millele pääseb ligi, kasutades \texttt{help()} või \texttt{?} süntaksit. Paljud paketid pakuvad ka sissejuhatavaid õpetusi ja veebipõhiseid juhendeid.

\section{MS Excel}\label{ms-excel}

MS Excel on laialdaselt kasutatav tabelarvutusprogramm, mis pakub mitmekülgseid tööriistu andmete analüüsimiseks, visualiseerimiseks ja esitlemiseks. MS Exceli kasutusvõimalused statistilise analüüsi tegemiseks hõlmavad mitmesuguseid funktsioone ja lisavahendeid, mis võimaldavad kasutajatel teostada põhjalikke analüüse erinevate andmekogumite põhjal. Järgnevalt on toodud ülevaade peamistest MS Exceli kasutusvõimalustest statistiliseks analüüsiks.

\textbf{Andmete importimine ja korraldamine}

\begin{itemize}
\tightlist
\item
  \textbf{Andmete importimine.} Excel võimaldab importida andmeid erinevatest allikatest, sealhulgas tekstifailidest, CSV-failidest, andmebaasidest ja veebiteenustest.
\item
  \textbf{Andmete puhastamine ja ettevalmistamine.} Kasutajad saavad kasutada tööriistu, nagu sortimine, filtreerimine ja eemaldamine, et korrastada andmeid analüüsi jaoks. Samuti on võimalik kasutada tingimusvormingut, et esile tõsta olulisi andmepunkte või mustreid.
\end{itemize}

\textbf{Andmete analüüsimine}

\begin{itemize}
\tightlist
\item
  \textbf{Põhilised statistilised funktsioonid.} Excel sisaldab mitmesuguseid statistilisi funktsioone, nagu keskmine (AVERAGE), mediaan (MEDIAN), standardhälve (STDEV), minimaalne (MIN) ja maksimaalne (MAX) väärtus.
\item
  \textbf{Liigendtabelid.} Liigendtabelid võimaldavad kiiresti kokku võtta, analüüsida, uurida ja esitada andmeid. Kasutajad saavad hõlpsasti grupeerida ja segmenteerida andmeid, et tuvastada mustreid või suundumusi.
\end{itemize}

\textbf{Statistilised testid ja analüüsimeetodid}

\begin{itemize}
\tightlist
\item
  \textbf{Hüpoteeside testimine.} Excelis saab teostada t-Testi ja ANOVA (Analysis of Variance) teste, et võrrelda andmekogumeid või analüüsida erinevusi rühmade vahel.
\item
  \textbf{Regressioonianalüüs.} Kasutajad saavad kasutada regressioonianalüüsi, et uurida muutujate vahelisi seoseid ja ennustada tulemusi.
\end{itemize}

\textbf{Andmete visualiseerimine}
- \textbf{Diagrammid ja graafikud.} Excel pakub erinevaid viise andmete visualiseerimiseks, sealhulgas tulp-, joon-, piirkonna-, ring-, hajuvus- ja mullidiagramme.
- \textbf{Tingimuslik vormindamine:} See võimaldab andmeid visuaalselt esile tõsta, kasutades värve, ikoone ja andmeribasid, et lihtsustada andmestiku mustrite ja trendide tuvastamist.

\textbf{Makrod ja VBA skriptimine}
- \textbf{Automatiseerimine ja kohandamine.} Kasutajad saavad luua makrosid ja kasutada Visual Basic for Applications (VBA) skriptimist, et automatiseerida korduvaid ülesandeid ja kohandada analüütilisi protseduure, mis ületavad Exceli standardfunktsioonide piire.

\textbf{Lisandmoodulid ja tööriistad}
- \textbf{Analysis ToolPak.} See on MS Exceli lisandmoodul, mis pakub täiendavaid statistilisi funktsioone, sealhulgas keerulisemaid analüütilisi tööriistu ja statistilisi meetodeid.

MS Exceli paindlikkus ja lai funktsionaalsus muudavad selle heaks tööriistaks statistiliseks analüüsiks. Siiski on oluline märkida, et keerukamate statistiliste analüüside ja suurte andmekogumite korral pakuvad spetsialiseeritud statistikatarkvarad rohkem võimalusi.

\chapter{Andmestik}\label{andmestik}

Metsanduses kogutakse pidevalt mitmesuguseid andmeid, mis võivad erineda nii oma tüübilt kui ka struktuurilt. Andmekogumise protsessi üldnimetus on \textbf{takseerimine}, mis hõlmab mitmesuguseid meetodeid nagu mõõtmine, loendamine, määramine ja muud sarnased tegevused. Iga takseerimisviis määrab ühtlasi ka kogutavate andmete tüübi.

\begin{itemize}
\tightlist
\item
  \textbf{Mõõtmisel} saadakse enamasti \textbf{pidev tunnus}. See on tunnus, mille väärtused võivad olla mistahes arvud teatud vahemikus. See tähendab, et pideva tunnuse puhul ei ole väärtused piiratud kindlate, eraldiseisvate arvudega, vaid võivad muutuda sujuvalt ja pidevalt. Näiteks mõõdetud puu kõrgus või diameeter.
\item
  \textbf{Loendamisel} saadakse \textbf{diskreetne tunnus}. See on tunnus, mille väärtused saavad olla ainult teatud kindlad, eraldiseisvad arvud, tavaliselt täisarvud. See tähendab, et diskreetsete tunnuste puhul ei saa väärtused olla sujuvad või pidevad, vaid peavad olema selgelt eristuvad. Näiteks puude ja aastarõngaste loendamine. Diskreetne on ka rinnaspindala mõõtmisel relaskoobiga loendamine, kus loendatakse puid, kuid teatud juhtudel kasutatakse ka konstanti 0,5.
\item
  \textbf{Määramisel} saadakse üldjuhul \textbf{nominaalne tunnus}. See on selline tunnus, mis väljendab kvalitatiivseid ehk mittearvulisi andmeid, mida ei saa järjestada. Näiteks puuliik, kasvukohatüüp vms. Selle alla liigitub ka \textbf{ordinaalne tunnus} ehk järjestustunnus on tunnus, mille väärtustel on loogiline järjestus, kuid väärtuste vahed ei ole tingimata võrdsed. Näiteks on metsanduses selleks boniteediklass.
\end{itemize}

Statistikas tähendab \textbf{andmestik} vaatlusandmete kogumit, mis on kogutud mingi uuringu või eksperimendi käigus. See on toorandmete hulk, mida analüüsitakse, et avastada mustreid, seoseid ja teha järeldusi. Andmete tüüp mängib olulist rolli statistilises analüüsis, kuna see määrab, milliseid meetodeid ja visualiseerimisviise saab kasutada. Õige andmetüübi tuvastamine on seega esimene samm edukaks andmetöötluseks ja tulemuste tõlgendamiseks.

Andmestik on organiseeritud andmete kogum, mis on tavaliselt salvestatud tabelitesse, andmebaasidesse või muudesse struktuuridesse.

\begin{itemize}
\tightlist
\item
  \textbf{Tüübid:}

  \begin{itemize}
  \tightlist
  \item
    \textbf{Vektor:} Sama tüüpi väärtuste jada (nt arvude vektor, tekstiväärtuste vektor).
  \item
    \textbf{Maatriks:} Sama tüüpi väärtuste kogum, kuid mis on mitmemõõtmeline.
  \item
    \textbf{Andmetabel:} Struktureeritud andmete kogum, kus iga rida esindab ühte objekti ja iga veerg esindab objekti atribuuti.
  \end{itemize}
\end{itemize}

\section{Andmestiku struktuur R keskkonnas}\label{andmestiku-struktuur-r-keskkonnas}

\subsection{Vektor}\label{vektor}

Vektor on andmetüüp, mis võimaldab talletada mitut ühesugust andmetüüpi elementi ühes andmestruktuuris. Vektoris saab hoida näiteks numbreid, teksti või loogilisi väärtusi. Vektorit loetakse ühemõõtmeliseks andmestruktuuriks, kuna kõik selles sisalduvad elemendid asuvad ühes reas.

Vektorit saab luua kasutades funktsiooni \texttt{c()}, kuhu tuleb sisestada eraldatud komadega elemendid. Näiteks:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\NormalTok{num\_vektor }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Vektori elementidele saab viidata indeksite abil, alustades indeksist 1. Näiteks:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\CommentTok{\# väljastab vektori num\_vektor kolmanda elemendi väärtuse}
\NormalTok{num\_vektor[}\DecValTok{3}\NormalTok{] }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3
\end{verbatim}

Vektori pikkus ehk elementide arv on võimalik saada funktsiooniga \texttt{length()}. Vektorit saab ühendada teise vektoriga funktsiooniga \texttt{c()}. Näiteks:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\NormalTok{num\_vektor\_2 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{6}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{)}
\NormalTok{kombineeritud\_vektor }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(num\_vektor, num\_vektor\_2)}
\end{Highlighting}
\end{Shaded}

Võimalik on ka vektorit luua jada genereerimise abil, kasutades funktsiooni \texttt{seq()}. Näiteks:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\CommentTok{\# loob vektori, mis sisaldab arve vahemikus 1 kuni 10 sammuga 2}
\NormalTok{jarg\_vector }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{by =} \DecValTok{2}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

Vektoritega on võimalik teostada erinevaid arvutusi, teisendusi ning andmete filtreerimist. Vektorid on olulised R programmeerimises, kuna nende abil on mugav töödelda andmeid ja teostada statistilisi analüüse.

\subsection{Maatriks}\label{maatriks}

Andmetüüp maatriks on kahe- või mitmemõõtmeline andmete struktuur, kus andmed on paigutatud mitme rea ja veeruna, moodustades seeläbi mitmemõõtmelise andmestiku. Maatriksis olevad andmed peavad olema kõik samatüübilised, näiteks kõik arvud või kõik tekstid.

Maatriksi loomiseks kasutatakse funktsioone \texttt{matrix()} või \texttt{array()}, millest esimene võimaldab luua kahemõõtmelist ning teine juba mitmemõõtmelisi maatrikseid. Nendele funktsioonidele saab määrata erinevaid parameetreid, näiteks andmete sisu, ridade ja veergude arvu ning rea- ja veerunimed.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}
\CommentTok{\# funktsioon runif() loob juhuslike andmete vektori}
\CommentTok{\# Loome kahemõõtmelise maatriksi juhuslikest arvudest}
\NormalTok{minu\_maatriks }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{runif}\NormalTok{(}\DecValTok{12}\NormalTok{), }\AttributeTok{nrow=}\DecValTok{3}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{4}\NormalTok{)}
\FunctionTok{print}\NormalTok{(minu\_maatriks)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
        [,1]    [,2]    [,3]    [,4]
[1,] 0,28887 0,83848 0,56844 0,81071
[2,] 0,45349 0,95911 0,15701 0,30945
[3,] 0,71799 0,63346 0,44702 0,96071
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Loome kolmemõõtmelise maatriksi juhuslikest arvudest}
\NormalTok{minu\_array }\OtherTok{\textless{}{-}} \FunctionTok{array}\NormalTok{(}\FunctionTok{runif}\NormalTok{(}\DecValTok{12}\NormalTok{), }\AttributeTok{dim =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Maatriksit saab kasutada erinevate arvutusoperatsioonide tegemiseks, nagu maatriksite korrutamine, liitmine, lahutamine jne. Samuti on võimalik maatriksit indekseerida ja välja printida konkreetseid ridu ja veerge.

\subsection{Andmetabel}\label{andmetabel}

R-i andmetüüp andmetabel (data.frame) on üks olulisemaid andmestruktuure andmete haldamiseks ja analüüsimiseks R-keskkonnas. Tabelis on andmed korraldatud ridade (vaatluste) ja veergude (tunnuste) kaupa. Iga veerg andmetabelis vastab ühele muutujale, mis võib olla numbriline, tekstiline või faktor. Iga rida esindab ühte andmepunkti, mis sisaldab väärtusi vastavatele muutujatele.

Andmetabeli loomiseks saab kasutada funktsiooni \texttt{data.frame()}. Andmed saab andmetabelisse importida erinevatest andmeallikatest (nt CSV-failid, andmebaasid) või genereerida otse R-s.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\CommentTok{\# Loome data.frame andmestiku}
\NormalTok{minu\_data\_frame }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =} \FunctionTok{runif}\NormalTok{(}\DecValTok{5}\NormalTok{), }\AttributeTok{y =} \FunctionTok{runif}\NormalTok{(}\DecValTok{5}\NormalTok{), }\AttributeTok{z =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Andmetabeli puhul on võimalik teha erinevaid andmehalduse ja analüüsi operatsioone nagu veergude ja ridade lisamine, kustutamine, filtreerimine, rühmitamine, sorteerimine ja statistiliste analüüside tegemine. Andmetabelil on oluline oskuslikult hallata ja kasutada, kuna see on väga levinud andmestruktuur R-keskkonnas ning võimaldab mugavalt töötada suurte andmekogumitega.

\subsection{List}\label{list}

R-i andmetüüp list on objektide kogu, mis võimaldab ühte muutujasse salvestada erineva pikkuse ja tüübiga andmeid. Üks list võib koosneda erinevatest vektoritest, maatriksitest või tabelitest.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\CommentTok{\# Loome list andmestiku}
\NormalTok{minu\_list }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
  \AttributeTok{x =} \FunctionTok{runif}\NormalTok{(}\DecValTok{5}\NormalTok{), }
  \AttributeTok{y =} \FunctionTok{array}\NormalTok{(}\FunctionTok{runif}\NormalTok{(}\DecValTok{16}\NormalTok{), }\AttributeTok{dim =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{)), }
  \AttributeTok{z =} \FunctionTok{c}\NormalTok{(}\StringTok{"MA"}\NormalTok{,}\StringTok{"KU"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\section{Andmestike importimine R keskkonda}\label{andmestike-importimine-r-keskkonda}

Andmete importimine CSV või Exceli failist R-i keskkonda on väga lihtne. Siin on näited mõlemast.

\textbf{Andmete importimine CSV failist}

Enne koodi käivitamist veendu, et CSV fail on salvestatud samas kaustas, kus Sa töötad R-is või et oled määranud õige tee failini.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\NormalTok{andmed }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"failinimi.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Kui CSV failil on teistsugune eraldusmärk (nt semikoolon), siis saab selle täpsustada lisades argumenti \texttt{sep=";"}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\NormalTok{andmed }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"failinimi.csv"}\NormalTok{, }\AttributeTok{sep=}\StringTok{";"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\textbf{Andmete importimine MS Exceli failist}

Esmalt tuleb installida ja laadida sisse \texttt{openxlsx} pakett, mis võimaldab Exceli failidest andmete lugemist.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Laadime peatükis kasutatavad paketid}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(readxl)}
\end{Highlighting}
\end{Shaded}

Seejärel kasutada funktsiooni \texttt{read\_excel()}, et importida andmed Exceli failist.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}

\NormalTok{andmed }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"failinimi.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\textbf{Arvutamine R-i keskkonnas}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Liitmine}
\DecValTok{1} \SpecialCharTok{+} \DecValTok{1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lahutamine}
\DecValTok{5} \SpecialCharTok{{-}} \DecValTok{3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Korrutamine}
\DecValTok{2} \SpecialCharTok{*} \DecValTok{4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Jagamine}
\DecValTok{10} \SpecialCharTok{/} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Astendamine}
\DecValTok{2} \SpecialCharTok{\^{}} \DecValTok{3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Jäägi leidmine}
\DecValTok{10} \SpecialCharTok{\%\%} \DecValTok{3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1
\end{verbatim}

R keskkonnas on võimalik teha arvutusi tsüklina

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Loome vektori 1st 10ni}

\ControlFlowTok{for}\NormalTok{(x }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)}
\NormalTok{\{}
\NormalTok{  y }\OtherTok{\textless{}{-}}\NormalTok{ x }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\chapter{Andmestike rühmitamine}\label{andmestike-ruxfchmitamine}

Pideva tunnuse rühmitamine tähendab andmete jaotamist gruppidesse või kategooriatesse vastavalt nende väärtustele. See on oluline statistilise analüüsi meetod, kui soovime analüüsida suurt hulka andmeid ning leida seoseid või mustreid nende vahel.

Pideva tunnuse rühmitamine võib olla vajalik mitmel põhjusel:

\begin{itemize}
\item
  Andmete lihtsustamine. Pidevate tunnuste rühmitamine võib muuta andmed hõlpsamini tõlgendatavaks ja analüüsitavaks, eriti juhul, kui on suur hulk erinevaid väärtusi.
\item
  Seoste või trendide avastamine. Rühmitades pidevaid tunnuseid, võime avastada seoseid või mustreid erinevate gruppide vahel. See võib aidata mõista näiteks, kuidas üks muutuja mõjutab teist või millised tegurid on omavahel seotud.
\item
  Statistilise analüüsi täpsus. Pidevate tunnuste rühmitamine võib parandada statistiliste analüüside täpsust ja usaldusväärsust, kuna see võib aidata vähendada andmete varieeruvust ning korrigeerida võimalikke moonutusi.
\end{itemize}

Seega on pideva tunnuse rühmitamine oluline statistilise analüüsi tööriist, mis aitab andmeid paremini mõista ja interpreteerida ning seeläbi teha järeldusi ja otsuseid põhinevalt faktidel ja statistilistel seostel.

\section{Jaotused}\label{jaotused}

\subsection{Empiiriline jaotus}\label{empiiriline-jaotus}

Empiiriline jaotus on statistilise andmestiku jaotus, mis põhineb tegelikel vaatlustel või mõõtmistel. See erineb teoreetilisest jaotusest, mis on abstraktne ja ideaalne jaotus, mida kasutatakse statistilistes mudelites ja analüüsides.

Empiiriline jaotus saadakse andmete kogumisel ja nende analüüsimisel, et mõista nähtuse tegelikku jaotust ja omadusi. See võib olla esitatud graafikuna (nt histogrammina) või matemaatilise mudelina, mis kirjeldab andmestiku jaotust.

Empiirilise jaotuse kasutamine on oluline, et saada parem arusaam uuritavast populatsioonist või nähtusest ning teha usaldusväärseid järeldusi statistiliste analüüside põhjal.

\subsection{Teoreetiline jaotus}\label{teoreetiline-jaotus}

Teoreetiline jaotus on statistikas abstraktne kontseptsioon, mis kirjeldab tõenäosust, et mingi nähtuse väärtus võtab teatud vahemiku või konkreetse väärtuse. Teoreetiline jaotus arvutatakse tavaliselt matemaatiliste mudelite abil ning see aitab meil mõista andmete tõenäosuslikku käitumist mingi statistilise populatsiooni või nähtuse puhul. Teoreetilised jaotused on olulised statistiliste analüüside läbiviimisel ning nende põhjal saab teha järeldusi ja prognoose erinevate metsandustega seotud uuringute kohta.

\section{Histogramm}\label{histogramm}

Histogramm ehk sagedusjaotuse tulpdiagramm on graafiline esitusviis andmehulga sageduste jaotumise näitamiseks. Histogramm koosneb üksteise kõrvale paigutatud tulpadest, kus iga tulp esindab teatud vahemikku või klassi, ning selle kõrgus näitab antud klassi sagedust. Horisontaaltelg esitab klasside vahemikke või kategooriaid ning vertikaaltelg näitab vastavate klasside sagedusi või sageduste suhtarvu. Histogrammi abil saab hinnata andmehulga jaotust ning tuvastada erinevaid tendentse ja mustreid andmetes. Histogrammi loomise eesmärgiks on anda visuaalne ülevaade andmete koondumisest ja levikust ning seeläbi paremini mõista andmete struktuuri. Histogrammi loomisel on oluline valida sobiv klassilaius, mis võimaldab õigesti tõlgendada ja analüüsida andmeid. Histogramm on oluline tööriist statistilise info esitamiseks ja mõistmiseks nii akadeemilistes kui ka praktilistes seadetes, sealhulgas metsanduses.

\begin{naidis}
Olgu juhuslikuks suuruseks puu diameeter. Antud näites on esitatud Järvseljal kvartalis 252  kasvanud 75 aasta vanuse naadisaariku saarepuude diameetri empiiriline jaotus proovitüki kluppimisandmete järgi. 
\end{naidis}

\subsection{R keskkonnas:}\label{r-keskkonnas}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Näide R keskkonnas}
\CommentTok{\# Laadime peatükis kasutatavad paketid}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

Esmalt loome pidevast tunnusest mõned juhuslikud andmed ning seejärel kuvame nende andmete põhjal histogrammi.

\textbf{Histogramm}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Laadime proovitükkide andmed}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ readxl}\SpecialCharTok{::}\FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/naited.xlsx"}\NormalTok{,}\StringTok{"prt\_andmed"}\NormalTok{)}

\CommentTok{\# koostame diameetrite histogrammi}
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(d)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(density)),}
    \AttributeTok{bins =} \DecValTok{15}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"white"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"black"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{y =} \StringTok{"f(x)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-22-1} \caption{Histogramm}\label{fig:unnamed-chunk-22}
\end{figure}

See kood loob R-keeles \texttt{ggplot2} paketiga graafiku, mis visualiseerib andmete jaotust. Vaatame seda samm-sammult:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{\texttt{ggplot(df,\ aes(x))}}: See alustab graafiku loomist. \texttt{df} on andmetabel, mis sisaldab andmeid. \texttt{aes(x)} määrab, et x-teljele kuvatakse muutujat \texttt{x}. See on graafiku ``põhi'', millele järgnevad kihid lisatakse.
\item
  \textbf{\texttt{geom\_histogram(...)}}: See lisab histogrammi.

  \begin{itemize}
  \tightlist
  \item
    \texttt{geom\_histogram()} funktsioon loob histogrammi, mis näitab andmete sagedust erinevatesse gruppidesse jaotatuna.
  \item
    \texttt{aes(y=after\_stat(density))} on oluline osa. See määrab, et y-teljel kuvatakse \emph{tihedust} (density), mitte lihtsalt sagedust (count). \texttt{after\_stat()} funktsiooniga pääsetakse ligi statistilisele väärtusele, mis arvutatakse histogrammi joonistamisel. Tihedus on normaliseeritud sagedus, nii et histogrammi pindala on 1. See võimaldab histogrammi ja tihedusfunktsiooni kõrvuti kuvada.
  \item
    \texttt{fill="white"} määrab histogrammi kastide sisemise värvi valgeks.
  \item
    \texttt{color="black"} määrab histogrammi kastide piirjoone värvi mustaks.
  \end{itemize}
\item
  \textbf{\texttt{geom\_density(color="red",\ lwd=1)}}: See lisab tihedusfunktsiooni graafikule.

  \begin{itemize}
  \tightlist
  \item
    \texttt{geom\_density()} funktsioon arvutab ja joonistab andmete tihedusfunktsiooni, mis on silutud kõver, mis näitab andmete jaotuse kuju.
  \item
    \texttt{color="red"} määrab tihedusfunktsiooni joone värvi punaseks.
  \item
    \texttt{lwd=1} määrab joone paksuse (line width) 1-ks.
  \end{itemize}
\item
  \textbf{\texttt{labs(y\ =\ "f(x)")}}: See lisab y-teljele sildi ``f(x)''. See on hea tava, et telgi selgelt märgistada, eriti kui y-telg näitab tihedust, mitte sagedust. ``f(x)'' on levinud tähistus tõenäosustihedusfunktsioonile (probability density function).
\end{enumerate}

\textbf{Sageduste arvutamine}

Tulpdiagrammile võib eelnevalt välja arvutada antud sagedused. Selleks saab kasutada funktsiooni \texttt{cut()}, mis vajab rühmade piire sisendiks ning seejärel saab juba funktsiooniga \texttt{table()} loendada kokku iga rühma liikmete arvu.

\subsection{Exceli keskkonnas:}\label{exceli-keskkonnas}

\subsubsection{Histogramm}\label{histogramm-1}

Histogrammi loomiseks Excelis peab andmed esmalt sisestama tabelisse ja seejärel kasutama selle jaoks sobivat tööriista.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Sisesta pideva tunnuse väärtused Exceli tabelisse.
\item
  Vali need lahtrid, kuhu soovid luua histogrammi.
\item
  Mine menüüsse ``Lisa'' ja vali ``Diagramm''.
\item
  Vali ``Histogramm'' ja klikka ``OK''.
\item
  Seejärel on võimalik vormindada telje suvandeid, millega määratakse rühmade (MS Exceli keskkonnas nimetusega ``salv'') parameetrid.
\end{enumerate}

\subsubsection{Sageduste arvutamine}\label{sageduste-arvutamine}

MS Exceli funktsioon \texttt{FREQUENCY()} võimaldab kasutajatel määrata, kui sageli väärtused esinevad teatud väärtusvahemikes. See funktsioon sobib hästi suurte andmekogumite analüüsimiseks, et mõista andmete jaotust ilma iga üksiku väärtuse manuaalse üle vaatamiseta.

Enne \texttt{FREQUENCY()} funktsiooni kasutamist peate määrama rühmade vahemike piirid, millesse soovite oma andmed jaotada. Need piirid tuleks sisestada eraldi veergu Exceli töölehel. Näiteks, kui soovite analüüsida testitulemusi vahemikus 0-100, võite määrata piirid 0, 20, 40, 60, 80, 100.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Andmete ja piiride sisestamine:}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Sisestage oma andmekogum ühte veergu (nt A2:A101).
\item
  Sisestage vahemike piirid teise veergu (nt B2:B7, eeldades, et esitasite näiteks eelmises punktis toodud piirid).
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Funktsiooni rakendamine:}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Valige tühi ala, kuhu soovite tulemused väljastada. Sellel peaks olema sama palju lahtrid kui määratletud vahemike piire. Kui teil on 6 piiri, valige 6 lahtrit vertikaalselt.
\item
  Sisestage \texttt{FREQUENCY()} funktsioon. Kuna \texttt{FREQUENCY()} on massiivifunktsioon, tuleb see sisestada massiivivalemiga. Algusesse minev andmevahemik on teie andmekogum ja teine vahemik on teie vahemike piirid.
  Näiteks: \texttt{=FREQUENCY(A2:A101,\ B2:B7)}
\item
  Pärast funktsiooni sisestamist lõpetage sisestus, vajutades \textbf{Ctrl+Shift+Enter}. Excel käitab nüüd \texttt{FREQUENCY()} funktsiooni massiivina ja täidab valitud lahtrid andmete sagedustega, mis vastavad määratud vahemikele.
\end{itemize}

\chapter{Karakteristikud}\label{karakteristikud}

Statistilised karakteristikud on kvantitatiivsed või kvalitatiivsed omadused, mis kirjeldavad ja iseloomustavad andmekogumeid või andmete jaotusi. Neid kasutatakse andmete kokkuvõtlikuks esitamiseks, et saada aru andmete üldisest käitumisest, trendidest ja omadustest. Statistilised karakteristikud võimaldavad teha järeldusi kogu populatsiooni kohta, analüüsides selleks valimit. Peamised statistilised karakteristikud jagunevad kaheks suureks rühmaks: keskmise ja hajuvuse karakteristikud.

Juhuslik suurus on täielikult kirjeldatud üldkogumi jaotus- või tihedusfunktsiooniga (jaotusega). Juhusliku suuruse iseloomustamiseks teatud aspektist kasutatakse erinevaid arvkarakteristikuid. Neist tähtsaim on \textbf{keskväärtus} ehk matemaatiline ootus, mida tähistatakse EX ja mis on defineeritud järgnevalt.

Pideva juhusliku suuruse korral:
\[EX = \sum_{-\infty}^{\infty} x \cdot f(x) dx\]

Diskreetse juhusliku suuruse korral:
\[EX = \sum_{i=1}^{n} x_i \cdot p_i\]

\section{Keskmised}\label{keskmised}

\subsection{Aritmeetiline keskmine}\label{aritmeetiline-keskmine}

Juhusliku suuruse jaotusseadus on uurijale enamasti teadmata. Seetõttu kasutatakse üldkogumi karakteristikute hindamiseks valimi vastavaid karakteristikuid. Üldkogumi keskväärtusele vastab valimi aritmeetiline keskmine, mida tähistatakse ülakriipsuga vastava muutuja kohal \(\bar x\) ja arvutatakse järgnevalt.

\[ \bar x=\frac{1}{N}\sum_{i=1}^{k}n_i \cdot x_i \]

Kus \(x_{i}\) on iga andmehulga liige ning \(n\) on andmehulga suurus.

\textbf{R keskkonnas:}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Laadime proovitükkide andmed}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ readxl}\SpecialCharTok{::}\FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/naited.xlsx"}\NormalTok{,}\StringTok{"prt\_andmed"}\NormalTok{)}
\CommentTok{\# Tunnusest arvutatakse keskmine:}
\FunctionTok{mean}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 23,265
\end{verbatim}

\textbf{Exceli keskkonnas:}

\begin{naideExcel}
=MEAN(andme_vektor)

\end{naideExcel}

\subsection{Ruutkeskmine}\label{ruutkeskmine}

Ruutkeskmine on üks keskmise leidmise meetoditest, mis annab ülevaate andmehulgast ning aitab mõõta andmete hajuvust. Ruutkeskmise leidmiseks tuleb iga andmehulga liige ruutu võtta, seejärel leida nende aritmeetiline keskmine ning võtta sellest ruutjuur. Matemaatiliselt väljendatuna on ruutkeskmine järgmine:

\[ \bar x_{ruut}=\sqrt{\frac{1}{N}\sum_{i=1}^{k}n_i \cdot x_i^2} \],

kus \(x_{i}\) on iga andmehulga liige ning \(n\) on andmehulga suurus.

Metsanduses on ruutkeskmine kasutusel keskmise diameetri arvutamisel.

\textbf{R keskkonnas:}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Tunnusest arvutatakse ruut ning keskmisest võetakse ruutjuur:}
\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{d}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 23,795
\end{verbatim}

\textbf{Exceli keskkonnas:}

\begin{naideExcel}
=SQRT(MEAN(andmeplokk^2))

\end{naideExcel}

\subsection{Geomeetriline keskmine}\label{geomeetriline-keskmine}

Geomeetriline keskmine on keskmise arvutamise meetod, mille puhul kõik antud arvud korrutatakse omavahel ning seejärel võetakse saadud korrutisest n-nda astme juur, kus n tähistab arvude kogust. Geomeetriline keskmine \(\bar x_{geom}\) arvutatakse järgneva valemiga:

\[\bar x_{geom}=\exp \biggl( \frac{1}{N}\sum_{i=n}^k n_i \cdot \ln(x_i) \biggr) \]

kus:

\begin{itemize}
\tightlist
\item
  \(n\) on arvude kogus
\item
  \(x_1, x_2, \ldots, x_n\) on positiivsed arvud
\end{itemize}

\textbf{R keskkonnas:}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Tunnusest arvutatakse logaritm ning keskmisest võetakse exponent:}
\FunctionTok{exp}\NormalTok{(}\FunctionTok{mean}\NormalTok{(}\FunctionTok{log}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{d)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 22,738
\end{verbatim}

\textbf{Exceli keskkonnas:}

\begin{naideExcel}
=GEOMEAN(andmeplokk)

\end{naideExcel}

\subsection{Harmooniline keskmine}\label{harmooniline-keskmine}

Harmooniline keskmine on statistiline mõõde, mis arvutatakse jagades arvude hulk nende vastandväärtuste summa järgi. Harmooniline keskmine on erinev aritmeetilisest ja geomeetrilisest keskmisest ning seda kasutatakse eelkõige siis, kui on vaja leida keskmine, mis arvestab vastandväärtusi või suhtarve.

Harmoonilist keskmist kasutatakse sageli olukordades, kus on vaja arvutada keskmine mingis suhtarvulises kontekstis, näiteks kiiruste, ajade või muude vastandväärtustega seotud suuruste puhul. Näiteks võib harmooniline keskmine kiirus olla kasulik, kui on vaja arvutada keskmine kiirus teepikkuse ja sõiduaegadega seotud olukorras.

Harmoonilist keskmist arvutatakse valemiga:
\[\bar x_{harm} = \frac{N}{\sum_{i=1}^k n_i / x_i},\]
kus \(x_{1}, x_{2}, \ldots, x_{n}\) on arvude hulk, mille harmoonilist keskmist soovitakse leida ning \(n\) on arvude hulga suurus.

\textbf{R keskkonnas:}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Tunnuse pöördväärtuse keskmisest võetakse pöördväärtus:}
\DecValTok{1}\SpecialCharTok{/}\FunctionTok{mean}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{df}\SpecialCharTok{$}\NormalTok{d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 22,222
\end{verbatim}

\textbf{Exceli keskkonnas:}

\begin{naideExcel}
=HARMEAN(andmeplokk)

\end{naideExcel}

\section{Kvantiilid}\label{kvantiilid}

Juhusliku suuruse p-kvantiiliks (0 \textless{} p \textless{} 1) nimetatakse sellist juhusliku suuruse väärtust xp, millest väiksemate väärtuste esinemise tõenäosus on p:

\[ P (X < x_p) = p \]

Teatud kvantiilide jaoks kasutatakse erinimetusi:

\begin{itemize}
\tightlist
\item
  \(x_{0,50}\) -- mediaan, tähistatakse ka Me;
\item
  \(x_{0,25}\) -- alumine kvartiil;
\item
  \(x_{0,75}\) -- ülemine kvartiil;
\item
  \(x_{0,10}\) -- alumine detsiil;
\item
  \(x_{0,9}\) -- ülemine detsiil;
\item
  \(x_{0,01}\) -- alumine protsentiil;
\item
  \(x_{0,99}\) -- ülemine protsentiil.
\end{itemize}

Enamkasutatavam kvantiil on \textbf{mediaan}, mida võib pidada (nagu keskväärtustki) juhusliku suuruse tsentriks. Mediaan on juhusliku suuruse selline väärtus, millest nii väiksemate kui ka suuremate väärtuste esinemise tõenäosus on 0,5. Mediaan iseloomustab juhusliku suuruse asendi poolest keskmist väärtust.
Kui on teada juhusliku suuruse jaotusfunktsioon F(x), siis saab juhusliku suuruse kvantiili xp arvutada kui jaotusfunktsiooni pöördfunktsiooni, sest kvantiili definitsioonist tuleneb F(xp) = p.~Juhul kui on tegemist vaatlusandmestikuga, saab kvantiile ligikaudu hinnata empiiriliselt jaotusfunktsiooni graafikult.

\section{Mediaan}\label{mediaan}

Mediaan väärtus, mis jagab andmed kaheks võrdselt suureks pooleks. See ei sõltu ekstreemsetest väärtustest ega hajutatud andmetest.

Mediaani arvutamine:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{median}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 23,2
\end{verbatim}

Exceli keskkonnas:

\begin{naideExcel}
=MEDIAN(andmeplokk)

\end{naideExcel}

\chapter{Jaotusfunktsioonid}\label{jaotusfunktsioonid}

\section{Hüpotees}\label{huxfcpotees}

Hüpotees on statistikas ja teadusuuringutes oluline mõiste, mis kujutab endast oletust või väidet üldkogumi kohta, mida soovitakse testida. Hüpoteesid on aluseks statistilisele analüüsile, võimaldades teha järeldusi valimi põhjal üldkogumi kohta. Hüpoteeside kontrollimise eesmärk on otsustada, kas andmed toetavad teatud väidet või mitte.

\textbf{Hüpoteeside liigid:}

\textbf{Nullhüpotees (\(H_0\)):} Nullhüpotees on väide, mille kohaselt oletatav seos või erinevus puudub, uuritav faktor ei mõjuta tunnuse jaotust või üldkogumi parameeter on võrdne teatud väärtusega. See on hüpotees, mida soovitakse ümber lükata või mille kehtivust testitakse. Nullhüpotees on seisukoht, mis kehtib vaikimisi, kuni on olemas piisavalt tõendeid selle ümberlükkamiseks. Näiteks võidakse püstitada nullhüpotees, et kahe grupi keskmised väärtused on võrdsed või et mingi muutuja jaotust ei mõjuta teine muutuja. Nullhüpoteesi püstitamine peab võimaldama selle ümberlükkamist.

\textbf{Sisukas hüpotees (\(H_1\)):} Sisukas hüpotees, mida nimetatakse ka alternatiivseks hüpoteesiks, on väide, mis on nullhüpoteesile vastand. See väljendab uurija ootust või arvamust, et mingi seos või erinevus on olemas või et uuritav faktor mõjutab tunnuse jaotust. Sisukas hüpotees on see, mida uurija soovib tõestada, seega on uurimise eesmärk leida piisavalt tõendeid, mis toetaksid sisuka hüpoteesi vastuvõtmist ja nullhüpoteesi ümberlükkamist. Näiteks, et kahe grupi keskmised väärtused erinevad või et mingi muutuja jaotus on mõjutatud teisest muutujast.

\textbf{Hüpoteeside püstitamine:}
Hüpoteese püstitatakse üldkogumi, mitte valimi kohta. Hüpoteeside kontrollimise loogika algab eeldusest, et nullhüpotees kehtib ning uuritakse, kui tõenäoline on antud andmete saamine nullhüpoteesi kehtimise korral. Hüpoteese on alati kaks, sest need peavad teineteist välistama. Üldjuhul on nii, et ühte hüpoteesi ümber lükates, võetakse vastu teine hüpotees.

\textbf{Hüpoteeside testimine:}
Hüpoteeside testimisel arvutatakse valimi andmete põhjal teststatistik. Teststatistiku väärtust võrreldakse teoreetilise jaotusega, mis on teada nullhüpoteesi kehtivuse korral. Kui valimi põhjal arvutatud teststatistiku väärtus on ebatõenäoline, loetakse nullhüpotees ümber lükatuks ja sisukas hüpotees tõestatuks. Oluline on mõista, et hüpoteese ei saa tõestada, vaid saab leida tõendeid nende toetuseks või vastuoluks. Kui andmed ei anna piisavalt tõendeid sisuka hüpoteesi kasuks, jäädakse nullhüpoteesi juurde. See ei tähenda, et nullhüpotees on tõestatud, vaid seda, et ei leitud piisavalt tõendeid selle ümberlükkamiseks.

\textbf{Vead hüpoteeside kontrollimisel:}
Hüpoteeside kontrollimisel on võimalik teha kaht liiki vigu:

\textbf{I liiki viga (\(\alpha\)):} I liiki viga tekib siis, kui otsustatakse sisukas hüpotees vastu võtta, kuigi tegelikult on õige nullhüpotees. See on vale positiivne järeldus, mis tähendab, et leitakse seos või erinevus, mida tegelikult ei ole. I liiki vea tegemise tõenäosust nimetatakse olulisuse nivooks ja tähistatakse sümboliga \(\alpha\). Üldiselt on I liiki vea tõenäosus seatud tasemele 0,05, mis tähendab, et on 5\% tõenäosus teha viga, kui nullhüpotees on õige. I liiki viga on enamasti raskemate tagajärgedega. I liiki vea tõenäosuse vähendamiseks tuleb vähendada olulisuse nivood.
\textbf{II liiki viga (\(\beta\)):} II liiki viga tekib siis, kui jäädakse nullhüpoteesi juurde, kuigi tegelikult on õige sisukas hüpotees. See on vale negatiivne järeldus, mis tähendab, et jäetakse leidmata seos või erinevus, mis tegelikult eksisteerib. II liiki viga on kergem viga, sest see tavaliselt tähendab, et soovitud tulemuste saamiseks on vaja rohkem andmeid koguda. Olulisuse nivoo vähendamine suurendab II liiki vea tõenäosust.

\textbf{Hüpoteeside liigid vastavalt suunale:}

\textbf{Kahepoolne hüpotees:} Kahepoolse hüpoteesi puhul testitakse, kas üldkogumi parameeter erineb teatud väärtusest, ilma et oleks määratud erinevuse suund. Näiteks, kas kahe grupi keskmised väärtused on erinevad (\(H_1: \mu_1 \neq \mu_2\)). Kahepoolse hüpoteesi korral on kriitiline piirkond mõlemal pool jaotuse keskmist.

\textbf{Ühepoolne hüpotees:} Ühepoolse hüpoteesi puhul testitakse, kas üldkogumi parameeter on suurem või väiksem teatud väärtusest. Ühepoolse hüpoteesi korral on kriitiline piirkond ühel pool jaotuse keskmist. Näiteks, kas ühe grupi keskmine on suurem kui teise grupi keskmine (\(H_1: \mu_1 > \mu_2\)) või vastupidi (\(H_1: \mu_1 < \mu_2\)).

Järgnevalt nimekiri täiendavatest statistika mõistetest, mida on oluline tunda hüpoteesi testimisel:

\textbf{Testimise protsess:}

\begin{itemize}
\tightlist
\item
  \textbf{Valim.} Populatsioonist võetud vaatluste kogum, mida kasutatakse hüpoteesi testimiseks.
\item
  \textbf{Valimstatistik.} Valimist arvutatud väärtus, mis iseloomustab valimit (nt keskmine, standardhälve).
\item
  \textbf{Teststatistik.} Arvutatud väärtus, mis võrdleb valimi statistikat nullhüpoteesis oletatud väärtusega.
\item
  \textbf{P-väärtus.} Tõenäosus saada valimi statistika, mis on sama ekstreemne või ekstreemsem kui tegelikult saadud statistika, eeldades, et nullhüpotees on tõene.
\item
  \textbf{Olulisuse nivoo (\(\alpha\)).} Ettenähtud tõenäosuse piir, mille alusel otsustatakse nullhüpotees ümber lükata. Tavaliselt on see 0,05 või 0,01.
\item
  \textbf{Järeldus.} Otsus, kas lükata nullhüpotees ümber või mitte, tuginedes p-väärtuse ja olulisuse nivoo võrdlemisele.
\end{itemize}

\textbf{Muud olulised mõisted:}

\begin{itemize}
\tightlist
\item
  \textbf{Ühepoolne test.} Hüpoteesi test, kus alternatiivne hüpotees määratleb suuna (nt keskmine on suurem kui).
\item
  \textbf{Kahepoolne test.} Hüpoteesi test, kus alternatiivne hüpotees ei määra suunda (nt keskmine on erinev).
\item
  \textbf{Usaldusnivoo.} Usaldusvahemikuga seotud kindluse tase, mis näitab usaldusvahemiku katvustõenäosust.
\item
  \textbf{Usaldusvahemik:} Väärtuste vahemik, mis teatud usaldusnivooga sisaldab populatsiooni parameetri tegelikku väärtust.
\item
  \textbf{Vabadusastmete arv:} Vaatlusandmete arv, mis on vabad varieeruma pärast statistiliste parameetrite hindamist.
\item
  \textbf{Jaotus:} Statistiline funktsioon, mis kirjeldab juhusliku muutuja võimalike väärtuste ja nende esinemise tõenäosusi (nt normaaljaotus, t-jaotus).
\end{itemize}

\section{Jaotusfunktsioon}\label{jaotusfunktsioon}

Jaotusfunktsioon on matemaatilise statistika mõiste, mis kirjeldab juhusliku suuruse väärtuste jaotust tõenäosuste kaudu. See seob iga juhusliku muutuja võimaliku väärtusega tõenäosuse, et muutuja väärtus on sellest väärtusest väiksem või sellega võrdne. Jaotusfunktsiooni tähistatakse tavaliselt \(F(x)\) või \(F_X(a)\), kus \(x\) või \(a\) tähistab reaalarvu, mille kohta tõenäosust arvutatakse. Seega,

\[F(x) = P(X \leq x),\]

kus \(X\) on juhuslik suurus ja \(P(X \leq x)\) on tõenäosus, et \(X\) võtab väärtuse, mis on väiksem või võrdne \(x\)-ga.

\textbf{Jaotusfunktsiooni olemus:}

\textbf{Kumulatiivne tõenäosus:} Jaotusfunktsioon esitab kumulatiivset tõenäosust, st see näitab, kui suure tõenäosusega on juhusliku suuruse väärtus mingist antud väärtusest väiksem või sellega võrdne.

\textbf{Diskreetse juhusliku suuruse jaotusfunktsioon:} Diskreetse muutuja puhul, mille väärtused on eraldiseisvad (nt täisarvud), on jaotusfunktsioon treppfunktsioon, mis kasvab hüppeliselt iga võimaliku väärtuse juures. Jaotusfunktsiooni väärtus on sel juhul iga konkreetse väärtuse tõenäosuste summa. Kui \(p_i\) on tõenäosus, et \(X = x_i\), siis diskreetse muutuja jaotusfunktsiooni võib kirjutada kui

\[F(a) = \sum_{x_i \leq a} p_i.\]

\textbf{Pideva juhusliku suuruse jaotusfunktsioon:} Pideva muutuja puhul, mille väärtused võivad olla mistahes arvud teatud vahemikus (nt pikkus, kaal), on jaotusfunktsioon pidev. Pideva muutuja puhul on iga üksiku väärtuse tõenäosus null, seega kasutatakse tihedusfunktsiooni, mis kirjeldab muutuja väärtuste jaotumist. Jaotusfunktsioon on sel juhul tihedusfunktsiooni \(f(x)\) integraal:

\[F(x) = \int_{-\infty}^{x} f(t) dt.\]

Graafiliselt vastab integraalile graafikualuse ala pindala integreeritavas vahemikus, mis tähendab, et sündmuse tõenäosus kuuluda etteantud väärtusvahemikku on võrdne väärtusvahemikku jääva tihedusfunktsiooni aluse pindalaga.

\textbf{Jaotusfunktsiooni omadused:} Jaotusfunktsioon on mittekahanev, mis tähendab, et see ei saa kahaneda, kui argument suureneb. Jaotusfunktsiooni piirväärtused on 0 ja 1, st \(\lim_{x \to -\infty} F(x) = 0\) ja \(\lim_{x \to \infty} F(x) = 1\), mis tähendab, et tõenäosus on vahemikus 0 ja 1. Samuti on jaotusfunktsioon paremalt pidev.

\textbf{Kasutusalad:} Jaotusfunktsiooni abil saab leida tõenäosusi, et juhuslik suurus \(X\) on väiksem või võrdne mingi arvuga \(a\) (\(P(X \leq a)\)), suurem mingist arvust \(b\) (\(P(X > b) = 1 - P(X \leq b)\)), või asub mingis vahemikus \(a\) kuni \(b\) (\(P(a < X \leq b) = F(b) - F(a)\)). Jaotusfunktsioon on oluline tööriist mitmesugustes statistilistes analüüsides ja modelleerimises.

\textbf{Näide:}

Kui meil on juhuslik suurus \(X\), mis näitab mündiviske tulemust (0 = ``kiri'' ja 1 = ``kull''), siis jaotusfunktsioon oleks järgmine:

\begin{itemize}
\tightlist
\item
  \(F(x) = 0\), kui \(x < 0\)
\item
  \(F(x) = 0.5\), kui \(0 \leq x < 1\)
\item
  \(F(x) = 1\), kui \(x \geq 1\)
\end{itemize}

See näide illustreerib diskreetse jaotusfunktsiooni, kus tõenäosus hüppab 0-lt 0,5-le ja sealt 1-le.

\textbf{Seos tihedusfunktsiooniga}

Pideva juhusliku suuruse puhul on tihedusfunktsioon \(f(x)\) jaotusfunktsiooni tuletis, ja jaotusfunktsioon on tihedusfunktsiooni integraal. Tihedusfunktsioon kirjeldab tõenäosustihedust juhusliku suuruse väärtuse ümber, ja jaotusfunktsioon kirjeldab kumulatiivset tõenäosust kuni teatud väärtuseni. Seega:

\[f(x) = \frac{dF(x)}{dx}\]

Jaotusfunktsiooni abil on võimalik arvutada tõenäosusi erinevate sündmuste toimumiseks. See on aluseks paljudele statistilistele meetoditele ja mudelitele, mis aitavad mõista ja prognoosida juhuslike suuruste käitumist.

\section{Normaaljaotus}\label{normaaljaotus}

Normaaljaotus, tuntud ka kui Gaussi jaotus, on pidev sümmeetriline jaotus, mida iseloomustab kellakujuline tihedusfunktsiooni graafik. See on statistikas üks olulisemaid jaotusi, kuna paljud juhuslikud suurused on ligikaudu normaaljaotusega või on teisendatavad normaaljaotusele alluvaks.

\textbf{Põhiomadused:}

\textbf{Sümmeetria:} Normaaljaotus on sümmeetriline keskväärtuse (\(\mu\)) suhtes. Keskväärtus, mediaan ja mood langevad kokku.

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-36-1} \caption{Normaajaotuse tihedusfunktsioon}\label{fig:unnamed-chunk-36}
\end{figure}

\textbf{Tihedusfunktsioon:} Normaaljaotuse tihedusfunktsioon on defineeritud järgmiselt:

\[f(x) = \frac{1}{\sigma \sqrt{2\pi}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}\]

kus:

\begin{itemize}
\tightlist
\item
  \(\mu\) on jaotuse keskväärtus (määrab jaotuskõvera asukoha).
\item
  \(\sigma\) on standardhälve (määrab jaotuskõvera laiuse - suurem \(\sigma\) tähendab laiemat ja madalamat kõverat).
\end{itemize}

\textbf{Tõenäosused ja Standardhälve:}

\begin{itemize}
\tightlist
\item
  \(P(\mu - \sigma \le X \le \mu + \sigma) \approx 0,683\) (68.3\% väärtustest jääb \(\pm 1\sigma\) vahemikku).
\item
  \(P(\mu - 2\sigma \le X \le \mu + 2\sigma) \approx 0,954\) (95.4\% väärtustest jääb \(\pm 2\sigma\) vahemikku).
\item
  \(P(\mu - 3\sigma \le X \le \mu + 3\sigma) \approx 0,997\) (99.7\% väärtustest jääb \(\pm 3\sigma\) vahemikku).
\end{itemize}

\textbf{Standardiseeritud Normaaljaotus (Z-jaotus):} Normaaljaotusega juhuslik suurus \(X\) saab teisendada standardiseeritud normaaljaotusele \(Z\) järgmise valemiga:

\[z = \frac{x - \mu}{\sigma}\]

Standardiseeritud normaaljaotuse puhul \(\mu = 0\) ja \(\sigma = 1\), tähistatakse \(N(0,1)\).

\textbf{Jaotusfunktsioon:} Kumulatiivne jaotusfunktsioon \(F(x)\) näitab tõenäosust \(P(X \le x)\) ja on tihedusfunktsiooni integraal. Normaaljaotuse jaotusfunktsioon on S-kujuline.

\textbf{Kasutusalad:}

\textbf{Statistilised Järeldused:} Normaaljaotus on aluseks paljudele statistilistele meetoditele (nt t-testid, ANOVA, regressioonanalüüs), mis sageli eeldavad andmete normaaljaotust. Suurte valimite puhul (n \textgreater{} 30) on võimalik teatud piirini eirata andmete kõrvalekaldumist normaaljaotusest.

\textbf{Protsesside Modelleerimine:} Paljud looduslikud ja majanduslikud nähtused on ligikaudu normaaljaotusega, olles mõjutatud mitmetest sõltumatutest juhuslikest teguritest.

\textbf{Eelised ja Piirangud:}

\textbf{Eelised:}

\begin{itemize}
\tightlist
\item
  Lihtne matemaatiline kirjeldus kahe parameetriga (\(\mu\) ja \(\sigma\)).
\item
  Laialdane kasutus ja põhjalikud teoreetilised alused.
\item
  Aluseks paljudele statistilistele testidele.
\item
  Tsentraalne piirteoreem tagab rakendatavuse valimite keskmiste analüüsil.
\end{itemize}

\textbf{Piirangud:}

\begin{itemize}
\tightlist
\item
  Ei sobi kõikide andmetüüpidega, eriti tugeva asümmeetria või erindite korral.
\item
  Reaalsed andmed harva täielikult vastavad normaaljaotusele.
\item
  Ebasobivate andmete korral võib anda eksitavaid tulemusi.
\end{itemize}

\section{T-jaotus}\label{t-jaotus}

T-jaotus, tuntud ka kui Studenti t-jaotus, on pidev tõenäosusjaotus, mis meenutab normaaljaotust, olles lamedam ja laiema sabaga. See on eriti kasulik statistikas väikeste valimite puhul (tavaliselt alla 30) ja kui üldkogumi standardhälve pole teada. T-jaotust rakendatakse peamiselt hüpoteeside testimisel, usaldusvahemike leidmisel ja valimi keskmise võrdlemisel üldkogumi keskväärtusega. T-jaotuse kuju sõltub vabadusastmete arvust (df - \emph{degrees of freedom}), mis on seotud valimi suurusega. Mida suurem on vabadusastmete arv, seda enam sarnaneb t-jaotus normaaljaotusega.

\textbf{T-jaotuse omadused ja tunnused:}

\textbf{Sümmeetria:} T-jaotus on sümmeetriline nulli ümber, sarnaselt standardsele normaaljaotusele. See tähendab, et jaotuse mõlemad pooled on keskmisest võrdsel kaugusel.

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-37-1} \caption{T-jaotuse tihedusfunktsioon}\label{fig:unnamed-chunk-37}
\end{figure}

\textbf{Tihedusfunktsioon:} T-jaotuse tihedusfunktsioon on keerukam kui normaaljaotusel ja sõltub vabadusastmete arvust. Valem on järgmine:

\[f(t) = \frac{\Gamma\left(\frac{\nu + 1}{2}\right)}{\sqrt{\nu\pi}\Gamma\left(\frac{\nu}{2}\right)} \left(1 + \frac{t^2}{\nu}\right)^{-\frac{\nu + 1}{2}}\]

kus \(\nu\) on vabadusastmete arv ja \(\Gamma\) on gammafunktsioon.

\textbf{Vabadusastmed (df):} T-jaotuse kuju määrab vabadusastmete arv. See arvutatakse valimi suuruse (\(n\)) põhjal. Ühe valimi t-testi korral on \(df = n - 1\), sõltumatute valimite t-testi korral \(df = n_1 + n_2 - 2\). Mida suurem on vabadusastmete arv, seda enam sarnaneb t-jaotus standardsele normaaljaotusele.

\textbf{Keskväärtus ja dispersioon:} T-jaotuse keskväärtus on 0, kui vabadusastmed on suuremad kui 1 (\(\nu > 1\)). Dispersioon sõltub vabadusastmetest ja on suurem kui 1 (\(\frac{\nu}{\nu-2}\), kui \(\nu>2\)).

\textbf{Kasutusala:} T-jaotust kasutatakse peamiselt juhul, kui valimi suurus on väike (tavaliselt \(n < 30\)) ja üldkogumi standardhälve on teadmata. Sellisel juhul ei saa kasutada standardset normaaljaotust.

\textbf{T-jaotuse rakendamine:}

\textbf{Hüpoteeside testimine:} T-jaotust kasutatakse hüpoteeside testimisel, kui võrreldakse valimi keskmist teatud väärtusega või kahe valimi keskmisi. Näiteks t-testi abil kontrollitakse, kas kahe grupi keskmised erinevad oluliselt. T-testid võivad olla ühepoolsed või kahepoolsed. Ühepoolset testi kasutatakse siis, kui on teada, mis suunas hüpotees peaks erinema. Kahepoolset testi rakendatakse, kui soovitakse kontrollida, kas erinevus üldse on olemas.

\textbf{Usaldusvahemikud:} T-jaotust rakendatakse usaldusvahemike leidmisel, kui hinnatakse, millises vahemikus paikneb üldkogumi keskväärtus antud valimi põhjal. Usaldusvahemik näitab, kui suur on tõenäosus, et tegelik keskmine väärtus jääb antud piiridesse.

\textbf{Regressioonanalüüs:} Regressioonanalüüsis rakendatakse t-jaotust regressioonimudeli parameetrite olulisuse testimiseks. Näiteks, et teha kindlaks, kas mingi muutuja mõjutab sõltuvat muutujat statistiliselt olulisel määral. Regressioonanalüüsi käigus hinnatakse mudeli parameetreid ja iga parameetri kohta arvutatakse t-statistik, mille abil otsustatakse, kas vastav muutuja on oluline mudeli seletusjõu seisukohalt.

\textbf{Järelduste tegemine väikeste valimitega:} T-jaotus on hädavajalik, kui valim on väike. Sellisel juhul ei saa kasutada normaaljaotust, mis eeldab suuremat valimit usaldusväärsete järelduste tegemiseks. T-jaotus võimaldab teha järeldusi ka väikeste valimite puhul, arvestades ebakindlust, mis kaasneb väikese valimi kasutamisega.

\textbf{Võrdlusülesanded:} T-test on statistiline meetod, mida kasutatakse kahe valimi keskmiste võrdlemiseks, eeldades, et andmed on normaalselt jaotunud või valimi suurus on piisavalt suur.

\textbf{T-testide liigid:}

\textbf{Ühe valimi t-test:} Kasutatakse, kui võrreldakse valimi keskmist teadaoleva või hüpoteetilise keskväärtusega.

\textbf{Sõltumatute valimite t-test:} Kasutatakse, kui võrreldakse kahe sõltumatu valimi keskmisi. See test eeldab, et andmed on mõlemas valimis ligikaudu normaalselt jaotunud ja et dispersioonid on ligikaudu võrdsed (või tehakse korrektsioon ebavõrdsete dispersioonide korral).

\textbf{Sõltuvate valimite t-test:} Kasutatakse, kui võrreldakse kahe sõltuva valimi keskmisi, kus iga vaatlus ühes valimis on seotud vastava vaatlusega teises valimis (näiteks mõõtmised enne ja pärast sekkumist).

\textbf{T-statistiku arvutamine:}

T-statistiku arvutamise valem sõltub kasutatavast t-testist, kuid üldine idee on leida valimi keskmise hälve hüpoteetilisest keskväärtusest või kahe valimi keskmise erinevus, jagatuna standardveaga. Ühe valimi t-testi puhul on valem järgmine:

\[t = \frac{\bar{x} - \mu}{s / \sqrt{n}}\]

kus \(\bar{x}\) on valimi keskmine, \(\mu\) on hüpoteetiline keskväärtus, \(s\) on valimi standardhälve ja \(n\) on valimi suurus.

\textbf{Vead t-testi rakendamisel:}

\textbf{I liiki viga (\(\alpha\)):} I liiki viga tekib siis, kui lükatakse tagasi nullhüpotees, kuigi see on tegelikult õige. See tähendab, et leitakse statistiliselt oluline erinevus, mida tegelikult ei ole. T-testi tulemustes on selle vea tõenäosus P(T\textless=t), mis tähistab tõenäosust, et t-statistik on võrdne või suurem antud väärtusest.

\textbf{II liiki viga (\(\beta\)):} II liiki viga tekib siis, kui ei lükata tagasi nullhüpoteesi, kuigi see on tegelikult vale. See tähendab, et ei leita statistiliselt olulist erinevust, kuigi see tegelikult eksisteerib.

\textbf{Olulisuse nivoo:}

Enne testi tegemist valitakse olulisuse nivoo (\(\alpha\)), mis määrab tõenäosuse teha I liiki viga. Tavaliselt kasutatakse olulisuse nivood 0,05, mis tähendab, et on 5\% tõenäosus teha I liiki viga. Olulisuse nivoo valik sõltub ka sellest, milliseid tagajärgi toob kaasa vea tegemine.

\section{F-jaotus}\label{f-jaotus}

F-jaotus on pidev tõenäosusjaotus, mida kasutatakse peamiselt dispersioonanalüüsis (ANOVA) ja hüpoteeside testimisel, eriti kahe või enama valimi dispersioonide võrdlemisel. See jaotus on statistikas oluline, kuna võimaldab hinnata, kas erinevused valimite dispersioonides on statistiliselt olulised või juhuslikud. F-jaotus on alati positiivne, sest see põhineb dispersioonide jagatisel, mis on alati positiivne.

\textbf{F-jaotuse omadused ja tunnused:}

\textbf{Pidevus:} F-jaotus on pidev jaotus, mis tähendab, et see hõlmab kõiki positiivseid reaalarve.

\textbf{Asümmeetria:} F-jaotus on parempoolse kaldega, asümmeetriline jaotus. Jaotuse tihedusfunktsioon ei ole sümmeetriline, jaotuse ``saba'' ulatub paremale poole.

\textbf{Parameetrid:} F-jaotust iseloomustavad kaks parameetrit: lugeja vabadusastmete arv (k) ja nimetaja vabadusastmete arv (h). Need vabadusastmed on seotud võrreldavate valimite suurustega.

\textbf{Vabadusastmed:} Vabadusastmed (degrees of freedom) tähistavad sõltumatute andmepunktide arvu, mida saab kasutada dispersiooni hindamiseks. Vabadusastmete arv mõjutab oluliselt F-jaotuse kuju.
\textbf{Tihedusfunktsioon:} F-jaotuse tihedusfunktsioon on defineeritud järgmiselt:

\[f(x) = \frac{\Gamma\left(\frac{k + h}{2}\right)}{\Gamma\left(\frac{k}{2}\right) \Gamma\left(\frac{h}{2}\right)} \left(\frac{k}{h}\right)^{\frac{k}{2}} x^{\frac{k}{2} - 1} \left(1 + \frac{k}{h} x\right)^{-\frac{k + h}{2}}, \quad x > 0\]
kus \(x\) on argument, \(\Gamma\) on gammafunktsioon, \(k\) on lugeja vabadusastmete arv ja \(h\) on nimetaja vabadusastmete arv. Valem näitab, kuidas F-jaotuse tihedus muutub argumendi \(x\) väärtuste korral.

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-38-1} \caption{T-jaotuse tihedusfunktsioon}\label{fig:unnamed-chunk-38}
\end{figure}

\textbf{Väärtuste vahemik:} F-jaotuse väärtused on alati positiivsed ja ulatuvad nullist lõpmatuseni.

\textbf{Kuju sõltuvus vabadusastmetest:} F-jaotuse kuju sõltub lugeja ja nimetaja vabadusastmetest. Suuremate vabadusastmete korral muutub jaotus sümmeetrilisemaks ja läheneb normaaljaotusele.

\textbf{F-jaotuse rakendused:}

\textbf{Dispersioonanalüüs (ANOVA):} F-jaotust kasutatakse peamiselt ANOVA-s, et testida, kas kahe või enama grupi keskmiste vahel on statistiliselt olulisi erinevusi. ANOVA-s arvutatakse F-statistik, mis on gruppidevahelise dispersiooni jagatis grupisisese dispersiooniga. Kui F-statistik on piisavalt suur, lükatakse tagasi nullhüpotees, mis väidab, et kõikide gruppide keskmised on võrdsed.

\textbf{Hüpoteeside testimine:} F-jaotust rakendatakse hüpoteeside testimisel, eriti dispersioonide võrdlemisel. Näiteks Levene'i test kasutab F-jaotust, et kontrollida, kas kahe või enama valimi dispersioonid on võrdsed. Seda tehakse sageli enne t-testi või ANOVA-t, veendumaks, et eeldus dispersioonide võrdsusest on täidetud.

\textbf{Regressioonanalüüs:} F-jaotust kasutatakse regressioonanalüüsis mudeli sobivuse hindamiseks. F-testi abil hinnatakse, kas regressioonimudel seletab olulisel määral sõltuva muutuja varieeruvust, võrreldes mudeliga, mis ei sisalda ühtegi seletavat muutujat.

\textbf{Kahe dispersiooni võrdlemine:} Kahe valimi dispersiooni võrdlemiseks kasutatakse F-testi, mis põhineb F-jaotusel. Teststatistiku arvutamiseks jagatakse suurem dispersioon väiksemaga. Seejärel võrreldakse saadud väärtust F-jaotuse kriitilise väärtusega, et teha kindlaks statistiline olulisus.

\textbf{Mudelite võrdlemine:} F-jaotust saab rakendada ka erinevate statistiliste mudelite võrdlemiseks, et selgitada välja, milline mudel sobib andmetega paremini. Näiteks mitme lineaarse regressiooni mudeli puhul saab F-testi abil võrrelda mudelite seletusjõudu ja parameetrite olulisust.

\textbf{F-statistiku arvutamine:}

F-statistiku arvutamise täpne valem sõltub konkreetsest testist või analüüsist, kuid üldpõhimõte on dispersioonide võrdlemine.

ANOVA-s defineeritakse F-statistik järgmiselt:

\[F = \frac{MST}{MSE}\]

kus \(MST\) on rühmadevaheline keskmine ruut (mean square between groups) ehk seletatud hajumine ja \(MSE\) on rühmasisene keskmine ruut (mean square within groups) ehk seletamata hajumine.

Kahe dispersiooni võrdlemisel arvutatakse F-statistik järgmiselt:

\[F = \frac{s_1^2}{s_2^2}\]
kus \(s_1^2\) on suurem dispersioon ja \(s_2^2\) on väiksem dispersioon.

\textbf{F-jaotuse seos teiste jaotustega:}

\textbf{\(\chi^2\)-jaotus:} F-jaotus on tihedalt seotud \(\chi^2\)-jaotusega. Kui kaks sõltumatut juhuslikku suurust \(X_k\) ja \(X_h\) alluvad \(\chi^2\)-jaotusele vabadusastmetega \(k\) ja \(h\), siis avaldis \(\frac{X_k/k}{X_h/h}\) allub F-jaotusele vabadusastmetega \(k\) ja \(h\).

\textbf{t-jaotus:} F-jaotust saab kasutada t-jaotuse tulemuste tuletamiseks. Kui \(t\) allub t-jaotusele vabadusastmega \(v\), siis \(t^2\) allub F-jaotusele vabadusastmetega 1 ja \(v\). Seega saab F-jaotust kasutada näiteks kahe valimi t-testi tulemuste kontrollimiseks ja usaldusväärsuse hindamiseks.

\textbf{Vead F-testi rakendamisel:}

\textbf{I liiki viga (\(\alpha\)):} I liiki viga tekib, kui lükatakse tagasi tõene nullhüpotees. See tähendab, et leitakse statistiliselt oluline erinevus, mida tegelikult ei eksisteeri.

\textbf{II liiki viga (\(\beta\)):} II liiki viga tekib, kui jäetakse tagasi lükkamata vale nullhüpotees. See tähendab, et ei leita statistiliselt olulist erinevust, mis tegelikult eksisteerib.

\section{\texorpdfstring{\(\chi^2\)-jaotus (hii-ruut-jaotus)}{\textbackslash chi\^{}2-jaotus (hii-ruut-jaotus)}}\label{chi2-jaotus-hii-ruut-jaotus}

\(\chi^2\)-jaotus ehk hii-ruut-jaotus on pidev tõenäosusjaotus, mida kasutatakse statistikas laialdaselt erinevate hüpoteeside testimiseks, eriti kategooriliste andmete puhul või dispersioonide hindamisel. See jaotus on asümmeetriline ja omab olulist rolli mitmetes statistilistes testides.

\textbf{\(\chi^2\)-jaotuse omadused ja tunnused:}

\textbf{Pidevus:} \(\chi^2\)-jaotus on pidev, mis tähendab, et see võib omandada mis tahes positiivseid väärtusi.

\textbf{Asümmeetria:} Jaotus on parempoolse kaldega, st jaotuse saba ulatub paremale ja tihedusfunktsioon ei ole sümmeetriline. Mida suurem on vabadusastmete arv, seda sümmeetrilisemaks jaotus muutub, lähenedes normaaljaotusele.

\textbf{Parameetrid:} \(\chi^2\)-jaotust iseloomustab üks parameeter: vabadusastmete arv (\(n\)). Vabadusastmed on seotud valimi suuruse ja analüüsis kasutatavate piirangutega.

\textbf{Vabadusastmed:} Vabadusastmed (degrees of freedom) tähistavad iseseisvate andmepunktide arvu, mis on kasutatavad dispersiooni hindamiseks. Vabadusastmete arv mõjutab oluliselt \(\chi^2\)-jaotuse kuju ja positsiooni.

\textbf{Tihedusfunktsioon:} \(\chi^2\)-jaotuse tihedusfunktsioon on määratud valemiga, kus parameetriks on vabadusastmete arv. Konkreetne valem on keeruline, aga oluline on teada, et see kirjeldab, kuidas \(\chi^2\)-jaotuse tihedus muutub sõltuvalt väärtusest ja vabadusastmetest.

\textbf{Väärtuste vahemik:} \(\chi^2\)-jaotuse väärtused on alati positiivsed ja ulatuvad nullist lõpmatuseni, kuna \(\chi^2\)-statistikud arvutatakse ruutude summana.

\textbf{Seos normaaljaotusega:} Kui sõltumatud juhuslikud suurused \(X_1, X_2, ..., X_n\) alluvad standardsele normaaljaotusele \(N(0, 1)\), siis nende ruutude summa, \(Y_n = \sum_{i=1}^n X_i^2\), allub \(\chi^2\)-jaotusele vabadusastmete arvuga \(n\). See seos on oluline, kuna see võimaldab seostada \(\chi^2\)-jaotust normaaljaotusega.

\textbf{Keskväärtus ja dispersioon:} \(\chi^2\)-jaotuse keskväärtus võrdub vabadusastmete arvuga (\(n\)) ja dispersioon on \(2n\).

\textbf{\(\chi^2\)-jaotuse kasutamine:}

\textbf{Hüpoteeside testimine:} \(\chi^2\)-jaotust kasutatakse laialdaselt erinevate hüpoteeside testimiseks, eriti kategooriliste andmete puhul. See hõlmab järgmisi olukordi:

\textbf{Sobivuse test:} \(\chi^2\)-sobivuse test (goodness-of-fit test) hindab, kas empiiriliste andmete jaotus vastab teoreetilisele jaotusele. Näiteks, kas mündiviske tulemused vastavad ootusele, et mõlemad pooled on võrdselt tõenäolised.

\textbf{Sõltumatuse test:} \(\chi^2\)-sõltumatuse test (test of independence) uurib, kas kaks kategoorilist muutujat on omavahel sõltuvad. Näiteks, kas haridustase ja sotsiaalmajanduslik staatus on omavahel seotud.

\textbf{Homogeensuse test:} \(\chi^2\)-homogeensuse test uurib, kas mitu valimit on pärit samast populatsioonist. Näiteks, kas erinevates piirkondades esineb samasugune osakaal erinevaid haridustasemeid.

\textbf{Dispersiooni hindamine:} \(\chi^2\)-jaotust kasutatakse ka valimi dispersiooni hindamisel, kui populatsioon on normaaljaotusega. Näiteks valimi standardhälbe usalduspiiride leidmisel.

\textbf{Vastavusanalüüs:} \(\chi^2\)-statistikut kasutatakse vastavusanalüüsis (correspondence analysis) kategooriliste muutujate vahelise seose hindamiseks ja visualiseerimiseks.

\textbf{Teguranalüüs:} \(\chi^2\)-testi kasutatakse ka teguranalüüsis, et hinnata mudeli sobivust andmetega.

\textbf{Pideva juhusliku suuruse testimine:} \(\chi^2\)-testi saab kasutada ka pidevate juhuslike suuruste korral, aga sel juhul tuleb variatsioonrida eelnevalt intervallida.

\textbf{\(\chi^2\)-statistiku arvutamine:}

\(\chi^2\)-statistiku arvutamise valem sõltub testitavast hüpoteesist, aga üldine idee on võrrelda vaadeldud sagedusi oodatavate sagedustega. Üldiselt arvutatakse \(\chi^2\)-statistik järgmiselt:

\[\chi^2 = \sum_{i=1}^k \frac{(O_i - E_i)^2}{E_i}\]

kus \(O_i\) on vaadeldud sagedus \(i\)-ndas kategoorias ja \(E_i\) on oodatav sagedus \(i\)-ndas kategoorias. Oodatav sagedus arvutatakse nullhüpoteesi kehtivuse korral.

\textbf{\(\chi^2\)-testi eeldused:}

\begin{itemize}
\tightlist
\item
  \textbf{Sõltumatud vaatlused:} Vaatlused peavad olema üksteisest sõltumatud.
\item
  \textbf{Oodatavad sagedused:} Oodatavad sagedused ei tohiks olla liiga väikesed (tavaliselt vähemalt 5 igas kategoorias). Liiga väikeste oodatavate sageduste korral võib test olla ebatäpne.
\item
  \textbf{Kategoorilised andmed:} \(\chi^2\)-test sobib peamiselt kategooriliste andmete analüüsiks. Pidevate andmete puhul tuleb need enne testi rakendamist kategooriatesse jaotada.
\end{itemize}

\textbf{\(\chi^2\)-jaotuse seos teiste jaotustega:}

\begin{itemize}
\tightlist
\item
  \textbf{F-jaotus:} \(\chi^2\)-jaotus on seotud F-jaotusega. Kui kaks sõltumatut \(\chi^2\)-jaotusega juhuslikku suurust jagatakse vastavate vabadusastmetega, siis nende jagatis allub F-jaotusele.
\item
  \textbf{Normaaljaotus:} Suure vabadusastmete arvu korral läheneb \(\chi^2\)-jaotus normaaljaotusele.
\end{itemize}

\textbf{Vead \(\chi^2\)-testi rakendamisel:}

\begin{itemize}
\tightlist
\item
  \textbf{I liiki viga (\(\alpha\)):} Esimest liiki viga tehakse siis, kui lükatakse tagasi nullhüpotees, kuigi see on tegelikult õige. See tähendab, et leitakse statistiliselt oluline erinevus, kuigi seda tegelikult ei ole.
\item
  \textbf{II liiki viga (\(\beta\)):} Teist liiki viga tehakse siis, kui ei lükata tagasi nullhüpoteesi, kuigi see on tegelikult vale. See tähendab, et ei leita statistiliselt olulist erinevust, kuigi see tegelikult eksisteerib.
\end{itemize}

\chapter{Statistilised hinnangud}\label{statistilised-hinnangud}

\section{Punkthinnangud}\label{punkthinnangud}

Mõistmaks punktihinnanguid, on oluline eristada valimi karakteristikuid üldkogumi vastavatest parameetritest. Punktihinnang on valimi andmetel arvutatud üksik väärtus, mida kasutatakse üldkogumi parameetri hindamiseks. Alljärgnevalt on kirjeldatud küsitud punktihinnangud, tuginedes antud allikatele.

\subsection{Valimi maht}\label{valimi-maht}

Valimi maht on valimisse kuuluvate elementide arv. Valimi mahu tähis on \(n\). Valimi maht on oluline, kuna see mõjutab hinnangute täpsust. Suurema valimi korral on hinnangud üldjuhul täpsemad ja usaldusväärsemad kui väikese valimi korral. Valimi suuruse määramiseks on olemas valemid, mis arvestavad soovitavat täpsust ja usaldusnivood.

\subsection{Aritmeetiline keskmine}\label{aritmeetiline-keskmine-1}

Aritmeetiline keskmine on valimi väärtuste summa jagatud valimi mahuga. See on mahukeskmine, mis tähendab, et selle väärtus sõltub igast üksikust valimi väärtusest. Aritmeetiline keskmine on efektiivne hinnang üldkogumi keskväärtusele, kuna see on nihketa ja väikseima hajuvusega hinnang. Aritmeetilise keskmise arvutamise valem on järgmine:

\[\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i\]

kus \(x_i\) on valimi elemendid ja \(n\) on valimi maht.

\begin{tabular}{ll}
MS Exceli funktsioon & =AVERAGE(vahemik)\\
R funktsioon & mean(vahemik) \\
\end{tabular}

\subsection{Dispersioon}\label{dispersioon}

Dispersioon on hälvete ruutude aritmeetiline keskmine. Dispersioon mõõdab andmete hajuvust keskmise ümber. Valimi dispersiooni tähistatakse \(s_x^2\). Dispersioon on alati positiivne suurus. Valimi dispersioon arvutatakse järgmise valemi abil:

\[s_x^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2\]

kus \(x_i\) on valimi elemendid, \(\bar{x}\) on valimi aritmeetiline keskmine ja \(n\) on valimi maht. Valemist on näha, et valimi dispersiooni arvutamisel kasutatakse jagajat \(n-1\). Jagajat \(n-1\) kasutatakse, et saada nihketa hinnang üldkogumi dispersioonile, sest kui kasutada jagajat \(n\), saadaksime nihkega hinnangu. Suure valimi korral (\(n > 100\)) on erinevus tühine, aga väikeste valimite korral erinevad need oluliselt.

\begin{tabular}{ll}
MS Exceli funktsioon & =VAR(vahemik)\\
R funktsioon & var(vahemik) \\
\end{tabular}

\subsection{Standardhälve}\label{standardhuxe4lve}

Standardhälve on ruutjuur dispersioonist. Standardhälve näitab, kui palju andmed keskmisest hajuvad. Valimi standardhälvet tähistatakse \(s_e\). Standardhälvet on mugav kasutada, kuna mõõtühik on sama, mis kirjeldataval tunnusel. Standardhälve on alati positiivne. Valimi standardhälve arvutatakse valemiga

\[s_x = \sqrt{s_x^2}\]

kus \(s^2\) on valimi dispersioon.

\begin{tabular}{ll}
MS Exceli funktsioon & =STDEV(vahemik)\\
R funktsioon & sd(vahemik) \\
\end{tabular}

\subsection{Standardviga}\label{standardviga}

Standardviga on valimi järgi arvutatud hinnangu standardhälve, mis kirjeldab üldkogumi keskväärtuse või muu parameetri valimist saadud hinnangu täpsust. See näitab, kui palju valimi keskmine võib tegelikust üldkogumi keskmisest erineda. Samast üldkogumist korduvalt võetud valimite keskväärtuste jaotus läheneb normaaljaotusele, mille standardhälve võrdub hinnangu standardveaga. Valimi keskmise standardviga arvutatakse valemiga

\[
s_{\bar{x}} = \frac{s_x}{\sqrt{N}}
\]

kus \(s_x\) on valimi standardhälve ja \(N\) on valimi maht.

\begin{tabular}{ll}
MS Exceli funktsioon & =STDEV(vahemik)/SQRT(COUNT(vahemik))\\
R funktsioon & sd(vahemik)/sqrt(length(vahemik)) \\
\end{tabular}

\subsection{Katsetäpsus}\label{katsetuxe4psus}

Katsetäpsus on suhteline standardviga protsentides. See näitab standardhälbe osakaalu aritmeetilisest keskmisest. Katsetäpsust arvutatakse järgmiselt:

\[
P_x 
= \frac{s_{\bar{x}}}{\bar{x}} \cdot 100 
= \frac{s_x}{\sqrt{N} \cdot \bar{x}} \cdot 100 
= \frac{V_x}{\sqrt{N}}
\]

kus \(V_x\) on variatsioonikordaja.

\begin{tabular}{ll}
MS Exceli funktsioon & =100*STDEV(H)/(AVERAGE(H)\*SQRT(COUNT(H))) \\
R funktsioon & 100*sd(H)/(mean(H)*sqrt(length(H))) \\
\end{tabular}

\subsection{Standardhälbe viga}\label{standardhuxe4lbe-viga}

Standardhälbe vea hinnang ehk standardhälbe standardhälve näitab, kui palju võib valimi standardhälve erineda üldkogumi standardhälbest. Standardhälbe viga arvutatakse järgmiselt:

\[s_{s_x} = \frac{s_x}{\sqrt{2 \cdot N}}\]

kus \(s_x\) on valimi standardhälve ja \(N\) on valimi maht.

\begin{tabular}{ll}
MS Exceli funktsioon & =STDEV(H)/SQRT(2*COUNT(H)) \\
R funktsioon & sd(H)/sqrt(2*length(H)) \\
\end{tabular}

\subsection{Dispersiooni viga}\label{dispersiooni-viga}

Dispersiooni vea hinnang ehk dispersiooni standardhälve arvutatakse valemiga

\[s_{s_x^2} = s_x^2 \cdot \sqrt{\frac{2}{N}}\]

kus \(s_x^2\) on valimi dispersioon ja \(N\) on valimi maht.

\begin{tabular}{ll}
MS Exceli funktsioon & =VAR(H)*SQRT(2/COUNT(H)) \\
R funktsioon & var(H)*sqrt(2/length(H))
\end{tabular}

\subsection{Variatsioonikordaja}\label{variatsioonikordaja}

Variatsioonikordaja on standardhälbe ja aritmeetilise keskmise suhe. Variatsioonikordaja on ühikuvaba suurus, mis võimaldab võrrelda erinevate ühikutes mõõdetud tunnuste varieeruvust. Variatsioonikordaja arvutatakse valemiga

\[V_x = 100 \cdot \frac{s_x}{\bar{x}}\]

\begin{tabular}{ll}
MS Exceli funktsioon & =100*STDEV(H)/AVERAGE(H)\\
R funktsioon & 100*sd(H)/mean(H) \\
\end{tabular}

\subsection{Variatsioonikordaja viga}\label{variatsioonikordaja-viga}

Variatsioonikordaja vea hinnang ehk variatsioonikordaja standardhälve arvutatakse valemiga

\[s_{V_x} = \frac{V_x}{\sqrt{2 \cdot N}}\]

\begin{tabular}{ll}
MS Exceli funktsioon & =100*STDEV(H)/(SQRT(2*COUNT(H))*AVERAGE(H)) \\
R funktsioon & 100*sd(H)/(sqrt(2*length(H))*mean(H)) \\
\end{tabular}

\section{Vahemikhinnangud}\label{vahemikhinnangud}

\subsection{Keskväärtuse usalduspiirid}\label{keskvuxe4uxe4rtuse-usalduspiirid}

\textbf{Keskväärtuse usalduspiirid} on statistilised vahendid, mis aitavad hinnata valimi põhjal tehtud järelduste täpsust üldkogumi keskväärtuse kohta. Need piirid moodustavad \textbf{usaldusvahemiku}, mis näitab, millises vahemikus võib üldkogumi tegelik keskväärtus asuda antud tõenäosusega. Usalduspiirid on seega usaldusvahemiku alumine ja ülemine piir.

Usaldusvahemik \textbf{ei ole} vahemik, mis sisaldab valimi väärtusi, vaid see on vahemik, mille sisse me usume tegeliku parameetri (üldkogumi keskväärtuse) langevat teatud tõenäosusega. See vahemik näitab, kui kindlad saame olla, et tegelik parameetri väärtus jääb antud vahemikku. Usaldusvahemikku kasutatakse, kuna valimist arvutatud hinnang on juhuslik suurus, samas kui üldkogumi parameetri tegelik väärtus ei ole juhuslik. Usaldusvahemiku leidmisel lähtutakse valimi keskmisest ja üldkogumi keskväärtus langeb antud usaldatavusega (tõenäosusega) sellesse vahemikku.

Usalduspiiride arvutamiseks kasutatakse valimi andmeid, valitakse teatud \textbf{usaldusnivoo} (tavaliselt 95\% või 99\%) ja arvutatakse vastav usaldusvahemik. Usaldusvahemiku arvutamiseks kasutatakse järgmist valemit:

\begin{itemize}
\tightlist
\item
  Alumine piir: \(\bar{x} - t_{\alpha/2, n-1} \cdot \frac{s_x}{\sqrt{n}}\)
\item
  Ülemine piir: \(\bar{x} + t_{\alpha/2, n-1} \cdot \frac{s_x}{\sqrt{n}}\)
\end{itemize}

kus:

\begin{itemize}
\tightlist
\item
  \(\bar{x}\) on valimi keskmine
\item
  \(t_{\alpha/2, n-1}\) on t-jaotuse \(\alpha/2\) täiendkvantiil vabadusastmete arvuga \(n-1\)
\item
  \(n\) on vaatluste arv ehk valimi suurus
\item
  \(s_x\) on valimi standardhälve
\item
  \(\alpha\) on olulisusnivoo (1 - usaldusnivoo)
\end{itemize}

Olulisusnivoo (\(\alpha\)) määrab tõenäosuse, et tegelik parameetri väärtus \textbf{ei jää} usaldusvahemikku. Teisisõnu, see on risk, millega oleme nõus eksima. Tavaliselt kasutatakse olulisusnivood 5\% (\(\alpha = 0,05\)) või 1\% (\(\alpha = 0,01\)). Mida väiksem on olulisusnivoo, seda laiem on usaldusvahemik (oleme kindlamad, et tegelik väärtus sinna jääb). Olulisusnivoo valik sõltub sellest, kumb viga on ohtlikum: kas kehtiva nullhüpoteesi tagasilükkamine (I liiki viga) või mittekehtiva nullhüpoteesi vastuvõtmine (II liiki viga). Praktikas peetakse I liiki vigu tavaliselt ohtlikumaks ja seetõttu eelistatakse madalamat olulisusnivood.

Usaldusvahemik võib olla \textbf{ühe-} või \textbf{kahepoolne}. \textbf{Kahepoolset} usaldusvahemikku kasutatakse siis, kui me soovime hinnata, kas tegelik parameeter võib olla nii suurem kui ka väiksem kui valimi keskmine. \textbf{Ühepoolset} usaldusvahemikku kasutatakse siis, kui oleme huvitatud ainult sellest, kas parameeter on suurem või väiksem kui teatud väärtus. Ühepoolse usalduspiiriga piirdumine on põhjendatud, kui hinnangu hälve vastassuunas on välistatud (nt mingi näitaja ei saa olla negatiivne). Kahepoolse testi puhul on \(t\)-väärtus arvutatud \(\alpha/2\) jaoks, ühepoolse testi puhul \(\alpha\) jaoks.

Väikese valimi korral ei pruugi eelnevalt toodud valemid olla täpsed, eriti osakaalude hindamisel. Ligikaudsest valemist leitud usaldusvahemiku alumine piir võib tulla negatiivne, mis ei ole reaalne (nt osakaal ei saa olla negatiivne). Sellisel juhul tuleks kasutada täpseid binoomjaotusel põhinevaid valemeid (nt Clopper-Pearsoni meetod). Suuremate valimite korral langevad täpse ja ligikaudse valemi tulemused kokku.

Keskväärtuse usalduspiiride leidmine ja hüpoteeside testimine on omavahel tihedalt seotud. Kui meil on nullhüpotees \(H_0: \mu = \mu_0\), siis kui valimi keskmine \(\bar{x}\) langeb piirkonda, kus olulisusnivool \(\alpha\) võetakse vastu \(H_0\), siis \(\mu_0\) asub valimi põhjal usaldatavusega \(\beta = 1-\alpha\) leitud keskväärtuse usaldusvahemikus. Hüpoteesi testimisel lähtume nullhüpoteesiga püstitatud väärtusest \(\mu_0\), aktsepteerimisvahemik on sellest mõlemale poole, ja me aktsepteerime nullhüpoteesi, kui valimi keskmine \(\bar{x}\) jääb sellesse vahemikku. Keskväärtuse usaldusvahemiku leidmisel lähtume aga valimi keskmisest \(\bar{x}\) ja üldkogumi keskväärtus \(\mu\) langeb antud usaldatavusega sellesse vahemikku.

\begin{naidis}
Vaatleme näites 1.4 esitatud valimit, milles on antud sambliku kasvukohatüübis kasvava 50-aastase männiku 60 juhuslikult valitud puu kõrguste andmed. Arvutame kõrguse keskväärtuse 95%-lised usalduspiirid.
\end{naidis}

Näites on selle valimi andmete põhjal arvutatud

\begin{tabular}{lr}
kõrguse aritmeetiline keskmine & 12,082 m \\
ja kõrguse standardhälve & 1,185 m \\
\end{tabular}

\textbf{MS Excel keskkonnas }

\(\mu_{0,025}\) = - TINV(0,05 ; N-1) * sh /SQRT(N) = 12,082 - 2,001·1,185/ = 11,78 m;

\(\mu_{0,975}\) = + TINV(0,05 ; N-1) * sh /SQRT(N) = 12,082 + 2,001·1,185/ = 12,39 m.

\textbf{R keskkonnas}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{korgus }\OtherTok{\textless{}{-}} \FunctionTok{as.vector}\NormalTok{(}\FunctionTok{unlist}\NormalTok{(readxl}\SpecialCharTok{::}\FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/naited.xlsx"}\NormalTok{,}\StringTok{"N14"}\NormalTok{, }\AttributeTok{col\_names =}\NormalTok{ F)))}
\NormalTok{korgus }\OtherTok{\textless{}{-}}\NormalTok{ korgus[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(korgus)]}
\NormalTok{N }\OtherTok{=} \FunctionTok{length}\NormalTok{(korgus)}
\NormalTok{H }\OtherTok{=} \FunctionTok{mean}\NormalTok{(korgus)}
\NormalTok{se }\OtherTok{=} \FunctionTok{sd}\NormalTok{(korgus)}
\NormalTok{H }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{,}\AttributeTok{df=}\NormalTok{N}\DecValTok{{-}1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(N)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 11,776
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{H }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\AttributeTok{df=}\NormalTok{N}\DecValTok{{-}1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(N)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 12,388
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Kordame sama funktsiooniga t.test}
\FunctionTok{t.test}\NormalTok{(korgus)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    One Sample t-test

data:  korgus
t = 79, df = 59, p-value <2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 11,776 12,388
sample estimates:
mean of x 
   12,082 
\end{verbatim}

\subsection{Dispersiooni usalduspiirid}\label{dispersiooni-usalduspiirid}

Dispersiooni usalduspiirid on statistiline tööriist, mis võimaldab hinnata, kui täpselt iseloomustab valimi dispersioon üldkogumi dispersiooni. Dispersioon kirjeldab andmete hajuvust keskväärtuse ümber ning usalduspiirid annavad meile vahemiku, milles teatud kindlusega (usaldusnivooga) asub tegeliku üldkogumi dispersiooni väärtus.

Dispersioon on statistiline mõõdik, mis näitab andmepunktide hajuvust keskmise ümber. Üldkogumi dispersiooni tähistatakse tavaliselt \(\sigma^2\) ja valimi dispersiooni \(s^2\). Valimi dispersioon on üldkogumi dispersiooni punkthinnang, kuid paratamatult esineb erinevus tegeliku väärtusega. Seega on dispersiooni usalduspiiride kasutamine oluline, et saada parem ülevaade tegeliku dispersiooni väärtusest.

Usaldusvahemik on väärtuste vahemik, mis teatud tõenäosusega sisaldab otsitava üldkogumi parameetri (antud juhul dispersiooni) tegelikku väärtust. Usalduspiirid on selle vahemiku alumine ja ülemine piir. Need piirid defineerivad ala, kuhu üldkogumi dispersioon langeb etteantud tõenäosusega (usaldusnivooga).

Dispersiooni usalduspiiride arvutamine on keerukam kui keskväärtuse usalduspiiride arvutamine. Tavaliselt kasutatakse selleks \(\chi^2\)-jaotust (hii-ruut-jaotust). \(\chi^2\)-jaotus on asümmeetriline jaotus, mille kuju sõltub vabadusastmete arvust. Valimi dispersiooni usalduspiirid \((1-\alpha)\) usaldusnivoo jaoks arvutatakse järgmiselt:

\begin{itemize}
\tightlist
\item
  Alumine piir: \(\frac{(n-1)s^2}{\chi^2_{\alpha/2, n-1}}\)
\item
  Ülemine piir: \(\frac{(n-1)s^2}{\chi^2_{1-\alpha/2, n-1}}\)
\end{itemize}

kus:

\begin{itemize}
\tightlist
\item
  \(n\) on valimi suurus
\item
  \(s^2\) on valimi dispersioon
\item
  \(\chi^2_{\alpha/2, n-1}\) on \(\chi^2\)-jaotuse \(\alpha/2\) kvantiil vabadusastmete arvuga \(n-1\)
\item
  \(\chi^2_{1-\alpha/2, n-1}\) on \(\chi^2\)-jaotuse \(1-\alpha/2\) kvantiil vabadusastmete arvuga \(n-1\)
\item
  \(\alpha\) on olulisusnivoo (ehk eksimisvõimalus)
\end{itemize}

\textbf{Standardhälbe usalduspiiride} saamiseks võetakse ruutjuur dispersiooni usalduspiiridest.

\begin{naidis}
Vaatleme näites 1.4 esitatud valimit, milles on antud sambliku kasvukohatüübis kasvava 50-aastase männiku 60 juhuslikult valitud puu kõrguste andmed. Arvutame kõrguse dispersiooni 95%-lised usalduspiirid.
\end{naidis}

Näites on selle valimi andmete põhjal arvutatud

\begin{tabular}{lr}
kõrguse aritmeetiline keskmine & 12,082 m \\
kõrguse dispersioon & 1,405 m \\
\end{tabular}

MS Exceli keskkonnas:

\[\sigma_{0,025}^2 = (N-1)*s_x^2/CHIINV(\alpha/2; N-1) = (60 - 1)*1,4046/82,12 = 1,01;\]
\[\sigma_{0,975}^2 = (N-1)*s_x^2/CHIINV(1-\alpha ; N-1) = (60 - 1)*1,4046/39,66 = 2,09.\]

R keskkonnas:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{N }\OtherTok{=} \FunctionTok{length}\NormalTok{(korgus)}
\NormalTok{H }\OtherTok{=} \FunctionTok{mean}\NormalTok{(korgus)}
\NormalTok{se2 }\OtherTok{=} \FunctionTok{var}\NormalTok{(korgus)}

\NormalTok{(}\AttributeTok{vra =}\NormalTok{ (N}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{se2}\SpecialCharTok{/}\FunctionTok{qchisq}\NormalTok{(}\FloatTok{0.975}\NormalTok{,N}\DecValTok{{-}1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1,0092
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\AttributeTok{vry =}\NormalTok{ (N}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{se2}\SpecialCharTok{/}\FunctionTok{qchisq}\NormalTok{(}\FloatTok{0.025}\NormalTok{,N}\DecValTok{{-}1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2,0894
\end{verbatim}

Saadud tulemuste põhjal võib väita, et valimi dispersioon on \text{1,405} ning 95\% tõenäosusega on dispersioon
vahemikus \text{1,009} m kuni \text{2,089} m Standardhälbe usalduspiiride saamiseks tuleb võtta saadud väärtustest ruutjuur -- \text{1,005} m kuni \text{1,445} m.

\subsection{Standardhälbe usalduspiirid}\label{standardhuxe4lbe-usalduspiirid}

Standardhälbe usalduspiirid on statistilised vahendid, mis aitavad hinnata üldkogumi standardhälbe \(\sigma\) määramise täpsust valimi standardhälbe \(s\) põhjal. Need piirid moodustavad usaldusvahemiku, mis näitab, millises vahemikus asub üldkogumi tegelik standardhälve \(\sigma\) antud usaldusnivooga (tõenäosusega). Standardhälve iseloomustab andmete hajuvust keskväärtuse ümber ja usalduspiirid on usaldusvahemiku alumine ja ülemine piir.

Standardhälbe usalduspiire arvutatakse sarnaselt dispersiooni usalduspiiride arvutamisega, kasutades \(\chi^2\)-jaotust (hii-ruut-jaotust). \(\chi^2\)-jaotus on asümmeetriline jaotus, mille kuju sõltub vabadusastmete arvust. Standardhälbe usalduspiirid \(1-\alpha\) usaldusnivoo korral arvutatakse järgmiselt:

\begin{itemize}
\tightlist
\item
  Alumine piir: \(L = \sqrt{\frac{(n-1)s^2}{\chi^2_{\alpha/2, n-1}}}\)
\item
  Ülemine piir: \(U = \sqrt{\frac{(n-1)s^2}{\chi^2_{1-\alpha/2, n-1}}}\)
\end{itemize}

kus:

\begin{itemize}
\tightlist
\item
  \(n\) on valimi suurus
\item
  \(s^2\) on valimi dispersioon (valimi standardhälbe ruut)
\item
  \(\chi^2_{\alpha/2, n-1}\) on \(\chi^2\)-jaotuse \(\alpha/2\) kvantiil vabadusastmete arvuga \(n-1\)
\item
  \(\chi^2_{1-\alpha/2, n-1}\) on \(\chi^2\)-jaotuse \(1-\alpha/2\) kvantiil vabadusastmete arvuga \(n-1\)
\item
  \(\alpha\) on olulisusnivoo (eksimise tõenäosus)
\end{itemize}

\subsection{Binoomjaotuse parameetri p usalduspiirid}\label{binoomjaotuse-parameetri-p-usalduspiirid}

Binoomjaotuse parameetri \emph{p} usalduspiirid annavad vahemiku, milles tõenäoliselt asub sündmuse tegelik toimumise tõenäosus \emph{p}, arvestades binoomjaotusega kirjeldatud katsete seeriat. Binoomjaotus on diskreetne tõenäosusjaotus, mis kirjeldab sõltumatute katsete seerias õnnestumiste arvu, kus igal katsel on kaks võimalikku tulemust: õnnestumine või ebaõnnestumine. Parameeter \emph{p} tähistab õnnestumise tõenäosust ühes katses.

Binoomjaotus on määratud kahe parameetriga: \emph{n} (katsete arv) ja \emph{p} (õnnestumise tõenäosus ühes katses). Binoomjaotust tähistatakse sageli B(\emph{n}, \emph{p}). Kui sooritame \emph{n} sõltumatut katset ja iga katse õnnestumise tõenäosus on \emph{p}, siis binoomjaotusega juhusliku suuruse X (õnnestumiste arv) tõenäosus on antud valemiga:

\[p_{\alpha/2} = \frac{k}{k + (n-k + 1) \cdot F_{\alpha/2,2 \cdot (n-k+1), 2\cdot k}}\]
\[p_{1- \alpha/2} = \frac{k+1}{(k+1)+(n-k) / F_{\alpha/2,2\cdot (k+1), 2 \cdot (n-k)}}\]

\begin{naidis}
Seemnepartii idanevustõenäosuse teadasaamiseks idandati partiist 70 juhuslikult valitud seemet, millest idanes 19. Leida seemnete idanevustõenäosuse usalduspiirid, võttes usaldusnivooks 0,95.
\end{naidis}

Seemnepartii idanevustõenäosuse 95\%-lised usalduspiirid avalduvad MS Excelis all-järgnevate valemitega:

\(p_{0,025}\) = k/(k+(n-k+1)\emph{FINV(0,025;2}(n-k+1);2*k)) = 19/(19+52·1,759) = 0,172;

\(p_{0,975}\) = (k+1)/((n-k)/FINV(0,025;2\emph{(k+1);2}(n-k))+k+1) = 20/(51/1,637+20) = 0,391.

R keskkonnas saab seda arvutada funktsiooniga \texttt{binom.test()}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{binom.test}\NormalTok{(}\DecValTok{19}\NormalTok{, }\DecValTok{70}\NormalTok{, }\DecValTok{19}\SpecialCharTok{/}\DecValTok{70}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    Exact binomial test

data:  19 and 70
number of successes = 19, number of trials = 70, p-value = 1
alternative hypothesis: true probability of success is not equal to 0,27143
95 percent confidence interval:
 0,17199 0,39098
sample estimates:
probability of success 
               0,27143 
\end{verbatim}

\section{Valimi mahu hindamine}\label{valimi-mahu-hindamine}

Üldkogumi parameetrite veahinnangud sõltuvad valimi mahust. Üldiselt tuleb hinnangu täpsuse suurendamiseks k korda suurendada valimi mahtu 2 * k korda. Praktilises metsanduslikus uurimistöös tekib tihti küsimus, kui palju tuleks mõõta puid, rajada proovitükke jne, et saadud tulemused iseloomustaksid üldkogumit piisava täpsusega.

\begin{naidis}
Vaatleme näites 1.4 esitatud valimit, milles on antud sambliku kasvukohatüübis kasvava 50-aastase männiku 60 juhuslikult valitud puu kõrguste andmed. 
\end{naidis}

Näites on selle valimi andmete põhjal arvutatud

\begin{tabular}{lr}
kõrguse aritmeetiline keskmine & 12,082 m \\
kõrguse standardhälve & 1,185 m \\
kõrguse variatsioonikordaja  & 9,81\% \\
\end{tabular}

Arvutame järgmise hinnangud:

\begin{itemize}
\tightlist
\item
  Puistu kõrguse keskväärtuse saamiseks katsetäpsusega \(\delta\) = 1\% tuleks mõõta

  \begin{itemize}
  \tightlist
  \item
    N = \((Vh/\delta)^2\) = \((9,81/1)^2\) \(\approx\) 96 puud.
  \end{itemize}
\item
  Puistu kõrguse keskväärtuse saamiseks standardveaga \(\epsilon\) = 0,1 m tuleks mõõta

  \begin{itemize}
  \tightlist
  \item
    N = \((sh/\epsilon)^2\) = \((1,185/0,1)^2\) \(\approx\) 140 puud.
  \end{itemize}
\item
  Puistu kõrguse keskväärtust veaga alla 0,1 m tuleks mõõta

  \begin{itemize}
  \tightlist
  \item
    N = \((NORMSINV(0,975)*sh/\epsilon)^2\) = \((1,96 * 1,185/0,1)^2\) \(\approx\) 539 puud.
  \end{itemize}
\end{itemize}

\section{Statistilised hüpoteesid}\label{statistilised-huxfcpoteesid}

\subsection{F-test normaaljaotusega üldkogumite dispersioonide võrdlemiseks}\label{f-test-normaaljaotusega-uxfcldkogumite-dispersioonide-vuxf5rdlemiseks}

F-test on statistiline test, mida kasutatakse kahe või enama normaaljaotusega üldkogumi dispersioonide võrdlemiseks. See test võimaldab hinnata, kas kahe valimi varieeruvus on oluliselt erinev, mis on oluline eeldus mitmete teiste statistiliste testide, näiteks t-testi, kasutamisel. F-testi kasutatakse nii kahepoolsete kui ka ühepoolsete hüpoteeside kontrollimiseks.

F-testi rakendamisel on oluline seada hüpoteesid, mida soovitakse testida. Hüpoteesid sõltuvad sellest, kas soovitakse testida dispersioonide erinevust üldiselt (kahepoolne test) või uurida, kas ühe kogumi dispersioon on suurem kui teise (ühepoolne test).

\begin{itemize}
\tightlist
\item
  \textbf{Kahepoolne hüpotees:}

  \begin{itemize}
  \tightlist
  \item
    Nullhüpotees (\(H_0\)): dispersioonid on võrdsed, st \(\sigma_1^2 = \sigma_2^2\).
  \item
    Alternatiivne hüpotees (\(H_1\)): dispersioonid on erinevad, st \(\sigma_1^2 \neq \sigma_2^2\).
  \end{itemize}
\item
  \textbf{Ühepoolne hüpotees:}

  \begin{itemize}
  \tightlist
  \item
    Nullhüpotees (\(H_0\)): ühe kogumi dispersioon on väiksem või võrdne teise kogumi dispersiooniga, st \(\sigma_1^2 \leq \sigma_2^2\) või \(\sigma_1^2 \geq \sigma_2^2\).
  \item
    Alternatiivne hüpotees (\(H_1\)): ühe kogumi dispersioon on suurem kui teise kogumi dispersioon, st \(\sigma_1^2 > \sigma_2^2\) või \(\sigma_1^2 < \sigma_2^2\).
  \end{itemize}
\end{itemize}

\textbf{Teststatistiku arvutamine}

F-statistiku arvutamiseks jagatakse suurema valimi dispersioon väiksemaga:

\(F = \frac{s_1^2}{s_2^2}\)

kus \(s_1^2\) ja \(s_2^2\) on valimite dispersioonid. On oluline, et lugejas oleks suurema dispersiooniga valim (seega alati \(F \geq 1\)). F-statistik allub F-jaotusele vabadusastmete arvudega \(n_1 - 1\) ja \(n_2 - 1\), kus \(n_1\) ja \(n_2\) on vastavate valimite mahud. F-jaotus on asümmeetriline ja selle kuju sõltub vabadusastmetest.

\textbf{Otsustamine ja kriitilised väärtused}

F-testi tulemuste tõlgendamiseks võrreldakse arvutatud F-statistiku väärtust kriitiliste väärtustega, mis saadakse F-jaotusest vastava olulisuse nivoo (\(\alpha\)) ja vabadusastmete alusel. Olulisuse nivoo on tavaliselt seatud 0,05-le, mis tähendab, et on 5\% tõenäosus teha I tüübi viga ehk lükata tagasi õige nullhüpotees.

\begin{itemize}
\tightlist
\item
  \textbf{Kahepoolse hüpoteesi korral} on kaks kriitilist väärtust, \(F_{krv}\) ja \(F_{krp}\), mis asuvad vastavalt F-jaotuse vasakul ja paremal pool. Nullhüpotees lükatakse tagasi, kui \(F < F_{krv}\) või \(F > F_{krp}\).

  \begin{itemize}
  \tightlist
  \item
    Vasakpoolne kriitiline väärtus: \(F_{krv} = F^{-1}_{\alpha/2}(n_2 - 1, n_1 - 1)\).
  \item
    Parempoolne kriitiline väärtus: \(F_{krp} = F_{\alpha/2}(n_1 - 1, n_2 - 1)\).
  \end{itemize}
\item
  \textbf{Ühepoolse hüpoteesi korral} (eeldades, et testime \(H_1: \sigma_1^2 > \sigma_2^2\)) on üks kriitiline väärtus, mis asub F-jaotuse paremal poolel. Nullhüpotees lükatakse tagasi, kui \(F > F_{kr}\). Kui testime \(H_1: \sigma_1^2 < \sigma_2^2\), siis asub kriitiline väärtus vasakul pool ja nullhüpotees lükatakse tagasi, kui \(F<F_{kr}\).

  \begin{itemize}
  \tightlist
  \item
    Parempoolne kriitiline väärtus (kui \(\sigma_1^2 > \sigma_2^2\)): \(F_{kr} = F_{\alpha}(n_1 - 1, n_2 - 1)\).
  \item
    Vasakpoolne kriitiline väärtus (kui \(\sigma_1^2 < \sigma_2^2\)): \(F_{kr} = F^{-1}_{\alpha}(n_2 - 1, n_1 - 1)\).
  \end{itemize}
\end{itemize}

\begin{naidis}
Olgu uurimisobjektiks suhteliselt homogeensel alal sambliku kasvu¬koha¬tüübi 24-aastased männikultuurid, millest osa on rajatud põlenud ja osa põlemata pinna¬sele. Põlenud alale rajati 8 ja põlemata alale 5 proovitükki. Proovitükkide andmete töötlemise tulemusel saadi järgmised puistute kõrgused meetrites.

Põlenud alal: 4,3; 3,4; 3,9; 2,9; 4,9; 3,2; 3,7; 3,6.

Põlemata alal: 4,8; 4,3; 5,4; 5,1; 4,6.
\end{naidis}

Meid huvitab, kas põlenud ja põlemata alal on puistute kõrguse dispersioonid erinevad.

MS Exceli funktsiooniga
=FTEST(andmeplokk1 ; andmeplokk2)
Antud näite korral on dispersioonide erinevuse olulisuse tõenäosus p = 0,47.

R keskkonnas saab selleks kasutada funktsiooni \texttt{var.test()}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{polenud }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{4.3}\NormalTok{, }\FloatTok{3.4}\NormalTok{, }\FloatTok{3.9}\NormalTok{, }\FloatTok{2.9}\NormalTok{, }\FloatTok{4.9}\NormalTok{, }\FloatTok{3.2}\NormalTok{, }\FloatTok{3.7}\NormalTok{, }\FloatTok{3.6}\NormalTok{)}
\NormalTok{polemata }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{4.8}\NormalTok{, }\FloatTok{4.3}\NormalTok{, }\FloatTok{5.4}\NormalTok{, }\FloatTok{5.1}\NormalTok{, }\FloatTok{4.6}\NormalTok{)}
\FunctionTok{var.test}\NormalTok{(polenud,polemata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    F test to compare two variances

data:  polenud and polemata
F = 2,2, num df = 7, denom df = 4, p-value = 0,47
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
  0,24249 12,15208
sample estimates:
ratio of variances 
            2,2004 
\end{verbatim}

\subsection{Keskmiste võrdlemine paarikaupa andmete korral normaaljaotusega üldkogumist}\label{keskmiste-vuxf5rdlemine-paarikaupa-andmete-korral-normaaljaotusega-uxfcldkogumist}

Paarikaupa andmete korral keskmiste võrdlemine normaaljaotusega üldkogumistest (sõltuvate valimite t-test) võimaldab hinnata, kas mingi toiming (nt protseduur, sekkumine) on põhjustanud statistiliselt olulise muutuse üldkogumi keskväärtuses. Seda tehakse, võrreldes sama objekti kahte mõõtmist (nt enne ja pärast toimingut).

\textbf{Hüpoteesid}

Paarikaupa andmete korral sõnastatakse hüpoteesid järgmiselt:

\begin{itemize}
\item
  \textbf{Nullhüpotees (\(H_0\)):} Toiming ei mõjutanud üldkogumi keskväärtust, st keskväärtuste vahe on null.
  \(H_0: \mu_1 = \mu_2\) või \(H_0: \mu_d = 0\), kus \(\mu_d\) on populatsiooni keskmine erinevus.
\item
  \textbf{Alternatiivne hüpotees (\(H_1\) või \(H_a\)):} Toiming mõjutas üldkogumi keskväärtust. Alternatiivne hüpotees võib olla:

  \begin{itemize}
  \tightlist
  \item
    \textbf{Kahepoolne:} Keskväärtus muutus (suund määramata).
    \(H_1: \mu_1 \neq \mu_2\) või \(H_1: \mu_d \neq 0\)
  \item
    \textbf{Ühepoolne:}

    \begin{itemize}
    \tightlist
    \item
      Keskväärtus suurenes: \(H_1: \mu_1 < \mu_2\) või \(H_1: \mu_d > 0\) (vaadates \emph{enne - pärast} erinevust, on oodatav erinevus positiivne)
    \item
      Keskväärtus vähenes: \(H_1: \mu_1 > \mu_2\) või \(H_1: \mu_d < 0\) (vaadates \emph{enne - pärast} erinevust, on oodatav erinevus negatiivne)
    \end{itemize}
  \end{itemize}
\end{itemize}

\textbf{Teststatistik}

Paarikaupa andmete korral arvutatakse t-statistik, kasutades iga paari mõõtmiste vahesid (\(d_i\)).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Vahede arvutamine:} \(d_i = x_{1i} - x_{2i}\), kus \(x_{1i}\) on \emph{i}-nda objekti esimene mõõtmine ja \(x_{2i}\) on \emph{i}-nda objekti teine mõõtmine.
\item
  \textbf{Vahede keskmise arvutamine:} \(\bar{d} = \frac{\sum_{i=1}^{n} d_i}{n}\), kus \(n\) on paaride arv.
\item
  \textbf{Vahede standardhälbe arvutamine:} \(s_d = \sqrt{\frac{\sum_{i=1}^{n} (d_i - \bar{d})^2}{n-1}}\)
\item
  \textbf{t-statistiku arvutamine:}
  \[t = \frac{\bar{d}}{s_d / \sqrt{n}}\]
\end{enumerate}

t-statistik järgib t-jaotust \(n-1\) vabadusastmega. t-jaotus on sümmeetriline, sarnaneb normaaljaotusega, kuid on väiksemate valimite korral laiema ``sabaga''.

\textbf{Otsuse tegemine}

Otsus nullhüpoteesi kohta tehakse, võrreldes arvutatud t-statistikut kriitilise väärtusega (\(t_{kr}\)) või hinnates p-väärtust.

\begin{itemize}
\tightlist
\item
  \textbf{Kriitiline väärtus (\(t_{kr}\)):} See leitakse t-jaotuse tabelist või statistikatarkvara abil, lähtudes valitud olulisuse nivost (\(\alpha\), tavaliselt 0.05) ja vabadusastmete arvust (\(n-1\)). Olulisuse nivoo \(\alpha\) tähistab I tüübi vea (valesti tagasilükatud tõese nullhüpoteesi) tõenäosust.

  \begin{itemize}
  \tightlist
  \item
    \textbf{Kahepoolse testi korral:} Nullhüpotees lükatakse tagasi, kui \(|t| > t_{kr}\), st \(t < -t_{kr}\) või \(t > t_{kr}\). Kriitiline väärtus \(t_{kr}\) vastab \(\alpha/2\) kummalgi jaotuse sabal.
  \item
    \textbf{Ühepoolse testi korral:}

    \begin{itemize}
    \tightlist
    \item
      Kui \(H_1: \mu_d > 0\): Nullhüpotees lükatakse tagasi, kui \(t > t_{kr}\).
    \item
      Kui \(H_1: \mu_d < 0\): Nullhüpotees lükatakse tagasi, kui \(t < -t_{kr}\).
    \end{itemize}
  \end{itemize}
\item
  \textbf{p-väärtus:} See on tõenäosus saada vähemalt sama äärmuslik (või veel äärmuslikum) t-statistik, kui nullhüpotees on tõene.

  \begin{itemize}
  \tightlist
  \item
    Nullhüpotees lükatakse tagasi, kui p-väärtus \(\leq \alpha\).
  \end{itemize}
\end{itemize}

\textbf{Eeldused}

Sõltuvate valimite t-testi eeldused on:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Normaaljaotus:} Mõõtmiste \emph{vahed} (\(d_i\)) peaksid olema ligikaudu normaaljaotusega. See eeldus on vähem oluline suuremate valimite korral (tänu tsentraalsele piirteoreemile).
\item
  \textbf{Sõltumatus:} Vaatlused (mõõtmispaarid) peavad olema üksteisest sõltumatud.
\item
  \textbf{Mõõtmiste skaala:} Mõõtmised on intervallskaalal või suhtarvulisel skaalal.
\end{enumerate}

\subsection{Sõltumatuse hii-ruut-test}\label{suxf5ltumatuse-hii-ruut-test}

Sõltumatuse hii-ruut-test ( \(\chi^2\)-test) on statistiline meetod, mida kasutatakse kahe kvalitatiivse tunnuse vahelise seose uurimiseks. Test hindab, kas kahe tunnuse jaotused on omavahel seotud või sõltumatud. Testi eesmärk on kummutada nullhüpotees (\(H_0\)), mis väidab, et tunnuste vahel seost ei ole.

\textbf{Põhimõtted ja rakendused}

\(\chi^2\)-testi kasutatakse sagedusandmete analüüsimiseks, mis on esitatud risttabelina (kontingentsitabelina). Risttabeli read esitavad ühe tunnuse väärtusi ja veerud teise tunnuse väärtusi. Test võimaldab uurida, kas ühe tunnuse jaotus sõltub teise tunnuse väärtustest. Näiteks saab testida, kas vastused küsimustele sõltuvad vastaja soost või vanusest. \(\chi^2\)-testi kasutatakse ka empiirilise ja teoreetilise jaotuse võrdlemiseks, et teha kindlaks, kas juhuslik suurus allub valitud jaotusseadusele.

\textbf{Hüpoteesid}

Sõltumatuse \(\chi^2\)-testi hüpoteesid on:

\begin{itemize}
\tightlist
\item
  \textbf{Nullhüpotees (\(H_0\)):} Tunnuste vahel seost ei ole (tunnused on sõltumatud). Ühe tunnuse jaotus ei sõltu teise tunnuse väärtustest.
\item
  \textbf{Alternatiivne hüpotees (\(H_1\)):} Tunnuste vahel on seos (tunnused ei ole sõltumatud). Ühe tunnuse jaotus sõltub teise tunnuse väärtustest.
\end{itemize}

\textbf{Teststatistiku arvutamine}

\(\chi^2\)-teststatistiku arvutamise valem:

\[
\chi^2 = \sum_{i=1}^{r} \sum_{j=1}^{k} \frac{(O_{ij} - E_{ij})^2}{E_{ij}}
\]

kus:

\begin{itemize}
\tightlist
\item
  \(O_{ij}\) on vaadeldud (empiiriline) sagedus risttabeli lahtris \emph{i, j}.
\item
  \(E_{ij}\) on oodatav sagedus risttabeli lahtris \emph{i, j}, kui tunnused oleksid sõltumatud.
\item
  \(r\) on ridade arv risttabelis.
\item
  \(k\) on veergude arv risttabelis.
\end{itemize}

Oodatava sageduse arvutamise valem:

\[
E_{ij} = \frac{(\text{rea } i \text{ summa}) \times (\text{veeru } j \text{ summa})}{\text{üldsumma}} = \frac{(\sum_{j=1}^{k} O_{ij}) \times (\sum_{i=1}^{r} O_{ij})}{\sum_{i=1}^{r} \sum_{j=1}^{k} O_{ij}}
\]

\textbf{Vabadusastmed}

Vabadusastmete arv (\(\nu\)) leitakse valemiga:

\[\nu = (r - 1) \times (k - 1)\]

\textbf{Otsuse tegemine}

Otsuse tegemiseks võrreldakse arvutatud \(\chi^2\) väärtust kriitilise väärtusega (\(\chi^2_{\alpha, \nu}\)), mis saadakse \(\chi^2\)-jaotusest vastava vabadusastmete arvu (\(\nu\)) ja valitud olulisuse nivoo (\(\alpha\)) alusel (tavaliselt \(\alpha = 0.05\)).

\begin{itemize}
\tightlist
\item
  Kui \(\chi^2 > \chi^2_{\alpha, \nu}\) või p-väärtus \(< \alpha\), siis lükatakse nullhüpotees tagasi ja järeldatakse, et tunnuste vahel on statistiliselt oluline seos.
\item
  Kui \(\chi^2 \leq \chi^2_{\alpha, \nu}\) või p-väärtus \(\geq \alpha\), siis jäädakse nullhüpoteesi juurde (ei saa tõestada, et tunnuste vahel on seos).
\end{itemize}

\textbf{Eeldused}

\(\chi^2\)-testi kasutamisel on oluline arvestada järgmisi eeldusi:

\begin{itemize}
\tightlist
\item
  \textbf{Sõltumatud vaatlused:} Vaatlused peavad olema üksteisest sõltumatud.
\item
  \textbf{Piisavalt suured oodatavad sagedused:} Üldjuhul peaksid kõik oodatavad sagedused (\(E_{ij}\)) olema vähemalt 5. Mõned allikad lubavad ka väiksemaid väärtusi, kuid kui rohkem kui 20\% oodatavatest sagedustest on alla 5, või on mõni oodatav sagedus alla 1, võib test olla ebausaldusväärne. Sellisel juhul võib kasutada Yates'i korrektsiooni või Fisheri täpset testi.
\end{itemize}

\chapter{Mitme tunnuse koosanalüüs}\label{mitme-tunnuse-koosanaluxfcuxfcs}

Mitme tunnuse koosanalüüs hõlmab mitmesuguseid statistilisi meetodeid, mille abil uuritakse, kuidas erinevad tunnused omavahel seostuvad ja üksteist mõjutavad. See analüüs on oluline, kuna reaalsetes olukordades mõjutavad uuritavat tunnust sageli mitmed tegurid korraga. Koosanalüüsi eesmärk on selgitada välja seosed tunnuste vahel, mõista nende mõju uuritavale nähtusele ja teha prognoose. Tunnuste koosanalüüs aitab minimeerida riski, et olulised seosed jäävad kahe silma vahele.

\section{Lineaarne regressioon}\label{lineaarne-regressioon}

Lineaarne regressioon on statistiline meetod, mida kasutatakse lineaarse seose modelleerimiseks sõltuva muutuja (funktsioontunnuse) ja ühe või mitme sõltumatu muutuja (argumenttunnuse) vahel. Eesmärk on leida sirge (või hüpertasapind mitme muutuja puhul), mis kõige paremini kirjeldab andmepunktide hajumist. See ``parim sobivus'' tähendab, et leitud sirge minimeerib vertikaalsete vahemaade summat andmepunktide ja sirge vahel.

Lineaarse regressiooni peamine eesmärk on:

\begin{itemize}
\tightlist
\item
  \textbf{Ennustamine.} Prognoosida sõltuva muutuja väärtust uute, seni tundmatute sõltumatute muutujate väärtuste korral.
\item
  \textbf{Seose mõistmine.} Mõista ja kvantifitseerida sõltumatute muutujate mõju sõltuvale muutujale. See aitab hinnata iga sõltumatu muutuja panust ja olulisust sõltuva muutuja varieerumises.
\end{itemize}

Lihtsa lineaarse regressiooni mudel (üks sõltumatu muutuja) on esitatav järgmise valemiga:

\[y_i = \beta_0 + \beta_1 x_i + \epsilon_i\]

kus:

\begin{itemize}
\tightlist
\item
  \(y_i\) on \(i\)-nda vaatluse sõltuv muutuja väärtus.
\item
  \(x_i\) on \(i\)-nda vaatluse sõltumatu muutuja väärtus.
\item
  \(\beta_0\) on regressioonisirge lõikepunkt (konstantne termin). See on \(y\) väärtus, kui \(x = 0\).
\item
  \(\beta_1\) on regressioonisirge kalle (koefitsient). See näitab, kui palju sõltuv muutuja \(y\) muutub, kui sõltumatu muutuja \(x\) suureneb ühe ühiku võrra.
\item
  \(\epsilon_i\) on veatermin, mis esindab kõiki muid faktoreid, mis mõjutavad \(y_i\), kuid mida mudelis ei arvestata. Eeldatakse, et veaterminid on juhuslikud, keskmise väärtusega null ja konstantse dispersiooniga.
\end{itemize}

Mitme lineaarse regressiooni mudel (mitu sõltumatut muutujat) on üldistus ülaltoodud mudelist:

\[y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + ... + \beta_p x_{pi} + \epsilon_i\]

kus:

\begin{itemize}
\tightlist
\item
  \(x_{ji}\) on \(i\)-nda vaatluse \(j\)-nda sõltumatu muutuja väärtus (kus \(j=1, 2, ..., p\) ja \(p\) on sõltumatute muutujate arv).
\item
  \(\beta_j\) on \(j\)-nda sõltumatu muutuja regressioonikoefitsient. See näitab, kui palju sõltuv muutuja \(y\) muutub, kui \(j\)-s sõltumatu muutuja \(x_j\) suureneb ühe ühiku võrra, eeldusel, et kõik teised sõltumatud muutujad jäävad konstantseks (ceteris paribus).
\item
  \(\beta_0\) on lõikepunkt.
\item
  \(\epsilon_i\) on veatermin.
\end{itemize}

Lineaarne regressioon arvutatakse tavaliselt \textbf{vähimruutude meetodit} (Ordinary Least Squares - OLS) kasutades. Vähimruutude meetodi eesmärk on minimeerida hälvete ruutude summat (RSS - Residual Sum of Squares) ehk ennustatud väärtuste ja tegelike väärtuste vahe ruutude summat.

RSS valem on:

\[RSS = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 = \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 x_{1i} + ... + \beta_p x_{pi}))^2\]

kus:

\begin{itemize}
\tightlist
\item
  \(n\) on vaatluste arv.
\item
  \(\hat{y}_i = \beta_0 + \beta_1 x_{1i} + ... + \beta_p x_{pi}\) on mudeli poolt ennustatud \(y_i\) väärtus.
\end{itemize}

Vähimruutude meetodi kasutamiseks tuleb leida sellised \(\beta_0, \beta_1, ..., \beta_p\) väärtused, mis minimeerivad RSS. See saavutatakse osatuletiste võtmisega RSS-ist iga \(\beta_j\) suhtes ja nende tuletiste nulliga võrdumise seadmisega. See annab \textbf{normaalvõrrandite süsteemi}.

Maatriksvormis saab lineaarset regressioonimudelit ja vähimruutude lahendust esitada elegantselt. Olgu \textbf{Y} vektor sõltuvatest muutujatest, \textbf{X} disainmaatriks (mis sisaldab sõltumatuid muutujaid ja konstantsammast ühtedest lõikepunkti jaoks) ja \textbf{\(\beta\)} koefitsientide vektor. Mudel on:

\[\mathbf{Y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\epsilon}\]

kus:

\begin{itemize}
\tightlist
\item
  \(\mathbf{Y} = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_n \end{bmatrix}\) on \(n \times 1\) vektor sõltuvate muutujate vaatlustest.
\item
  \(\mathbf{X} = \begin{bmatrix} 1 & x_{11} & x_{21} & \cdots & x_{p1} \\ 1 & x_{12} & x_{22} & \cdots & x_{p2} \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 1 & x_{1n} & x_{2n} & \cdots & x_{pn} \end{bmatrix}\) on \(n \times (p+1)\) disainmaatriks. Esimene veerg on ühtedest lõikepunkti jaoks, ja järgmised veerud on sõltumatute muutujate vaatlused.
\item
  \(\boldsymbol{\beta} = \begin{bmatrix} \beta_0 \\ \beta_1 \\ \vdots \\ \beta_p \end{bmatrix}\) on \((p+1) \times 1\) vektor regressioonikoefitsientidest.
\item
  \(\boldsymbol{\epsilon} = \begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \vdots \\ \epsilon_n \end{bmatrix}\) on \(n \times 1\) vektor veaterminitest.
\end{itemize}

Vähimruutude lahendus koefitsientide vektorile \(\boldsymbol{\hat{\beta}}\) on antud järgmise valemiga:

\[\boldsymbol{\hat{\beta}} = (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{Y}\]

Eeldusel, et \((\mathbf{X}^T\mathbf{X})\) on pööratav. See on peamine valem regressioonikoefitsientide arvutamiseks.

Pärast regressioonimudeli arvutamist on oluline hinnata selle sobivust ja statistilist olulisust. Peamised teststatistikud ja hindamise meetodid on järgmised:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{\(R^2\) ja kohandatud \(R^2\):}

  \begin{itemize}
  \tightlist
  \item
    \textbf{\(R^2\) (determinatsioonikordaja).} Mõõdab, kui suure osa sõltuva muutuja varieeruvusest suudab regressioonimudel seletada. \(R^2\) väärtused jäävad vahemikku 0 kuni 1. Mida lähemal on \(R^2\) väärtusele 1, seda paremini mudel andmeid sobitab.
  \item
    Valem \(R^2\) arvutamiseks:
    \[R^2 = 1 - \frac{RSS}{TSS} = 1 - \frac{\sum_{i=1}^{n} (y_i - \hat{y}_i)^2}{\sum_{i=1}^{n} (y_i - \bar{y})^2}\]
    kus \(TSS\) on hälvete ruutude summa (Total Sum of Squares) ja \(\bar{y}\) on sõltuva muutuja keskmine väärtus.
  \item
    \textbf{Kohandatud \(R^2\).} Parandab \(R^2\) puudust, mis alati suureneb sõltumatute muutujate arvu lisandumisel, isegi kui need muutujad ei ole olulised. Kohandatud \(R^2\) karistab mudelit ebavajalike muutujate lisamise eest.
  \item
    Valem kohandatud \(R^2\) arvutamiseks:
    \[\text{Kohandatud } R^2 = 1 - \frac{(1-R^2)(n-1)}{n-p-1}\]
    kus \(n\) on vaatluste arv ja \(p\) on sõltumatute muutujate arv mudelis (ilma lõikepunktita).
  \end{itemize}
\item
  \textbf{RMSE (ruutkeskmine viga):}

  \begin{itemize}
  \tightlist
  \item
    RMSE mõõdab mudeli ennustusvigade standardhälvet. See annab aimu, kui suur on tüüpiline erinevus ennustatud ja tegelike väärtuste vahel. Madalam RMSE näitab paremat mudeli ennustustäpsust.
  \item
    Valem RMSE arvutamiseks:
    \[RMSE = \sqrt{\frac{RSS}{n}} = \sqrt{\frac{\sum_{i=1}^{n} (y_i - \hat{y}_i)^2}{n}}\]
  \end{itemize}
\item
  \textbf{Koefitsientide statistiline olulisus (t-test):}

  \begin{itemize}
  \tightlist
  \item
    Iga regressioonikoefitsiendi \(\beta_j\) (välja arvatud \(\beta_0\)) puhul saab testida nullhüpoteesi \(H_0: \beta_j = 0\), mis tähendab, et \(j\)-ndal sõltumatul muutujal puudub seos sõltuva muutujaga (kui kõik teised muutujad on konstantsed).
  \item
    T-testi statistiku arvutamine koefitsiendi \(\beta_j\) jaoks:
    \[t = \frac{\hat{\beta}_j}{SE(\hat{\beta}_j)}\]
    kus \(SE(\hat{\beta}_j)\) on \(\hat{\beta}_j\) standardviga. Standardvea saab arvutada mudeli veaterminite dispersiooni ja disainmaatriksi \(\mathbf{X}\) põhjal.
  \item
    Saadud t-statistikut võrreldakse t-jaotuse kriitiliste väärtustega (või arvutatakse p-väärtus), et otsustada nullhüpoteesi tagasilükkamine. Madal p-väärtus (tavaliselt alla 0.05) viitab, et koefitsient on statistiliselt oluline ja sõltumatu muutuja avaldab olulist mõju sõltuvale muutujale.
  \end{itemize}
\item
  \textbf{Mudeli üldine olulisus (F-test):}

  \begin{itemize}
  \tightlist
  \item
    F-test testib nullhüpoteesi, et kõik regressioonikoefitsiendid (välja arvatud \(\beta_0\)) on samaaegselt null \(H_0: \beta_1 = \beta_2 = ... = \beta_p = 0\). See test hindab, kas mudel tervikuna on statistiliselt oluline ja kas on vähemalt üks sõltumatu muutuja, mis aitab sõltuva muutuja varieeruvust seletada.
  \item
    F-statistiku arvutamine:
    \[F = \frac{MSS}{MSE} = \frac{RSS_{null} - RSS_{mudel}}{RSS_{mudel}} \times \frac{n-p-1}{p}\]
    kus \(MSS\) on mudeli ruutude keskmine summa (Model Sum of Squares), \(MSE\) on vigade ruutude keskmine summa (Mean Squared Error), \(RSS_{null}\) on RSS mudeli korral, mis sisaldab ainult lõikepunkti (nullmudel), ja \(RSS_{mudel}\) on RSS uuritava mudeli korral.
  \item
    F-statistikut võrreldakse F-jaotuse kriitiliste väärtustega (või arvutatakse p-väärtus), et otsustada nullhüpoteesi tagasilükkamine. Madal p-väärtus (tavaliselt alla 0.05) viitab, et mudel on statistiliselt oluline.
  \end{itemize}
\end{enumerate}

\section{Lineaarse regressiooni eelduste selgitus}\label{lineaarse-regressiooni-eelduste-selgitus}

Lineaarse regressiooni rakendamine on võimas meetod seoste modelleerimiseks, kuid selle tulemuste usaldusväärsus sõltub teatud eelduste täitmisest. Need eeldused tagavad, et vähimruutude meetod annab parimad võimalikud ja usaldusväärsed hinnangud regressioonikoefitsientidele ja mudeli statistilisele olulisusele. Vaatame neid eeldusi ükshaaval põhjalikumalt:

\begin{itemize}
\item
  \textbf{Lineaarsus:} Eeldatakse, et sõltuva muutuja ja sõltumatute muutujate vaheline seos on lineaarne. See tähendab, et sõltuva muutuja muutuse ennustatakse iga sõltumatu muutuja ühiku muutuse kohta konstantse suurusega.

  \begin{itemize}
  \tightlist
  \item
    \textbf{Mida see tähendab:} Graafiliselt kujutades peaks andmepunktide hajumine järgima sirget joont (lihtsa lineaarse regressiooni puhul) või hüpertasapinda (mitmese lineaarse regressiooni puhul). Formaalselt öeldes tähendab see, et oodatav väärtus sõltuvale muutujale on lineaarne funktsioon sõltumatutest muutujatest.
  \item
    \textbf{Miks see oluline on:} Kui tegelik seos ei ole lineaarne, siis lineaarse regressiooni mudel ei suuda seost adekvaatselt kirjeldada. Lineaarne mudel võib anda eksitavaid ennustusi ja valed järeldused muutujate seoste kohta.
  \item
    \textbf{Kuidas kontrollida:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Hajuvusdiagrammid:} Sõltuva muutuja hajuvusdiagrammi joonistamine iga sõltumatu muutuja suhtes aitab visuaalselt hinnata lineaarsust.
    \item
      \textbf{Jääkide diagrammid:} Jääkide (tegelike ja ennustatud väärtuste vahe) diagrammi joonistamine ennustatud väärtuste või sõltumatute muutujate suhtes. Lineaarsuse korral peaks jääkide hajumine olema juhuslikult jaotunud nulljoone ümber, ilma süstemaatilise mustrita. Mitte-lineaarsuse korral võib diagrammil näha kõveraid mustreid.
    \end{itemize}
  \item
    \textbf{Mis juhtub, kui eeldus on rikutud:} Lineaarne mudel võib anda halbu ennustusi ja valed järeldused.
  \item
    \textbf{Mida teha:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Muutujate transformeerimine:} Sõltuva ja/või sõltumatute muutujate transformeerimine (näiteks logaritm, ruutjuur, ruut) võib mõnikord muuta mittelineaarse seose lineaarseks.
    \item
      \textbf{Polünoomiline regressioon:} Lineaarse mudeli asemel võib kasutada polünoomilist regressiooni, mis võimaldab modelleerida mittelineaarseid seoseid polünoomide abil.
    \item
      \textbf{Mittelineaarne regressioon:} Kui seos on teadaolevalt mittelineaarne ja transformatsioonid ei aita, võib kasutada mittelineaarset regressiooni meetodit, mis on spetsiifiliselt loodud mittelineaarsete seoste modelleerimiseks.
    \end{itemize}
  \end{itemize}
\item
  \textbf{Sõltumatus:} Iga vaatlus peab olema sõltumatu teistest vaatlustest. See tähendab, et ühe vaatluse väärtus ei tohiks olla mõjutatud teiste vaatluste väärtustest.

  \begin{itemize}
  \tightlist
  \item
    \textbf{Mida see tähendab:} Iga andmepunkt peaks olema kogutud või genereeritud sõltumatult teistest andmepunktidest. Näiteks, kui me uurime individuaalsete inimeste andmeid, eeldame, et ühe inimese andmed ei mõjuta teise inimese andmeid.
  \item
    \textbf{Miks see oluline on:} Sõltumatuse eeldus on oluline standardvigade korrektseks hindamiseks ja seega ka statistilise olulisuse testide ja usaldusvahemike usaldusväärsuseks. Kui vaatlused on sõltuvad, siis standardvead võivad olla alahinnatud, mis viib valejäreldusteni statistilise olulisuse kohta (mudel näib statistiliselt olulisem kui see tegelikult on).
  \item
    \textbf{Kuidas kontrollida:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Andmete kogumise protsessi mõistmine:} Hoolikalt tuleb kaaluda, kuidas andmed on kogutud. Kas on potentsiaalseid sõltuvuse allikaid? Näiteks aja-reas andmetes (andmed, mis on kogutud aja jooksul järjestikku) on sageli sõltuvus, kus eilne väärtus võib mõjutada tänast väärtust. Samuti võib sõltuvust esineda klasterandmetes (näiteks õpilased klassides, patsiendid arstides), kus grupis olevad vaatlused võivad olla sarnasemad kui grupidest väljaspool olevad vaatlused.
    \item
      \textbf{Durbin-Watson test (aja-rea andmete korral):} Durbin-Watson test on spetsiifiliselt loodud autokorrelatsiooni (sõltuvuse) tuvastamiseks jääkides aja-rea andmetes.
    \end{itemize}
  \item
    \textbf{Mis juhtub, kui eeldus on rikutud:} Standardvead on ebatäpsed, mis teeb statistilised testid ja usaldusvahemikud ebausaldusväärseks.
  \item
    \textbf{Mida teha:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Aja-rea mudelid:} Kui tegemist on aja-rea andmetega ja sõltuvus on autokorrelatsioon, võib kasutada aja-rea mudelite (näiteks ARIMA mudelid) asemel lineaarselt regressiooni.
    \item
      \textbf{Segamõjudega mudelid (klasterandmete korral):} Kui tegemist on klasterandmetega, võib kasutada segamõjudega mudeleid (mixed-effects models), mis võtavad arvesse grupisisese sõltuvuse.
    \item
      \textbf{Robustsed standardvead:} Teatud juhtudel, kui sõltuvust ei saa täielikult modelleerida, saab kasutada robustseid standardvigu (näiteks Huber-White standardvead), mis on vähem tundlikud sõltuvuse suhtes (kuigi need ei lahenda probleemi täielikult).
    \end{itemize}
  \end{itemize}
\item
  \textbf{Homoskedastilisus:} Jääkide dispersioon (variatsioon) peaks olema konstantne kõigi sõltumatute muutujate väärtuste korral. See tähendab, et jääkide ``hajuvus'' peaks olema ühtlane kogu regressioonisirge pikkuses. Heteroskedastilisus on homoskedastilisuse vastand ja tähendab, et jääkide dispersioon ei ole konstantne, vaid muutub sõltuvalt sõltumatute muutujate väärtustest.

  \begin{itemize}
  \tightlist
  \item
    \textbf{Mida see tähendab:} Jääkide hajumisdiagrammil ennustatud väärtuste või sõltumatute muutujate suhtes peaks jääkide punktide ``laius'' olema enam-vähem sama kogu ulatuses.
  \item
    \textbf{Miks see oluline on:} Homoskedastilisus on oluline vähimruutude meetodi efektiivsuse tagamiseks. Kuigi vähimruutude meetod annab ikka erapooletud hinnangud koefitsientidele ka heteroskedastilisuse korral, on hinnangud ebaefektiivsed (neil on suurem dispersioon kui vaja oleks) ja standardvead on jälle ebatäpsed, mis mõjutab statistiliste testide ja usaldusvahemike usaldusväärsust.
  \item
    \textbf{Kuidas kontrollida:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Jääkide hajumisdiagrammid:} Jääkide diagrammi joonistamine ennustatud väärtuste või iga sõltumatu muutuja suhtes. Homoskedastilisuse korral peaks jääkide hajumine olema juhuslik ja ühtlane riba ümber nulljoone. Heteroskedastilisuse korral võib diagrammil näha mustreid, näiteks jääkide ``laiuse'' suurenemine või vähenemine koos ennustatud väärtuste või sõltumatu muutuja väärtustega (näiteks ``lehviku'' kuju).
    \item
      \textbf{Breusch-Pagan test ja White'i test:} Need on formaalsed statistilised testid heteroskedastilisuse testimiseks. Need testid hindavad, kas jääkide ruudud on seotud sõltumatute muutujate või nende ruutudega.
    \end{itemize}
  \item
    \textbf{Mis juhtub, kui eeldus on rikutud:} Vähimruutude hinnangud on ebaefektiivsed ja standardvead on ebatäpsed.
  \item
    \textbf{Mida teha:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Muutujate transformeerimine:} Sõltuva muutuja transformeerimine (näiteks logaritm, ruutjuur) võib mõnikord vähendada heteroskedastilisust, eriti kui heteroskedastilisus on seotud sõltuva muutuja tasemega.
    \item
      \textbf{Robustsed standardvead:} Nagu sõltumatuse puhul, saab ka heteroskedastilisuse korral kasutada robustseid standardvigu (näiteks Huber-White standardvead). Need annavad usaldusväärsemad standardvead ja seega ka usaldusväärsemad statistilised testid ja usaldusvahemikud, isegi kui heteroskedastilisus on olemas.
    \item
      \textbf{Kaalutud vähimruudud (Weighted Least Squares - WLS):} WLS meetod on spetsiifiliselt loodud heteroskedastilisuse probleemi lahendamiseks. See meetod annab suuremad kaalud vaatlustele, millel on väiksem jääkide dispersioon, ja väiksemad kaalud vaatlustele, millel on suurem jääkide dispersioon, et ``ühtlustada'' variatsiooni.
    \end{itemize}
  \end{itemize}
\item
  \textbf{Normaaljaotus:} Jäägid peaksid olema ligikaudselt normaaljaotusega. See eeldus kehtib eelkõige statistiliste testide ja usaldusvahemike usaldusväärsuse jaoks, eriti väikeste valimite korral. Suurte valimite korral, tänu keskväärtusteoreemile, on regressioonikoefitsientide hinnangud ligikaudu normaalselt jaotunud isegi siis, kui jäägid ei ole täpselt normaalselt jaotunud (kuid siiski peaksid olema homoskedastilised ja sõltumatud).

  \begin{itemize}
  \tightlist
  \item
    \textbf{Mida see tähendab:} Jääkide histogramm peaks meenutama kellakujulist normaaljaotust. Jääkide teoreetiline jaotus peaks olema normaalne.
  \item
    \textbf{Miks see oluline on:} Normaaljaotuse eeldus on oluline, et kasutada t-teste koefitsientide statistilise olulisuse testimiseks ja F-testi mudeli üldise olulisuse testimiseks, eriti väikeste valimite korral. Kui jäägid on normaalselt jaotunud, siis koefitsientide hinnangud on ka normaalselt jaotunud ja teststatistikud järgivad t- ja F-jaotusi vastavalt. Kui jäägid ei ole normaalselt jaotunud (eriti kui valim on väike), siis võivad testide p-väärtused ja usaldusvahemikud olla ebatäpsed.
  \item
    \textbf{Kuidas kontrollida:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Histogramm ja tihedusdiagramm:} Jääkide histogrammi ja tihedusdiagrammi joonistamine aitab visuaalselt hinnata, kas jäägid on ligikaudu normaalselt jaotunud.
    \item
      \textbf{Normaalsuse Q-Q diagramm (Quantile-Quantile plot):} Q-Q diagramm võrdleb jääkide kvantiile teoreetilise normaaljaotuse kvantiilidega. Kui jäägid on normaalselt jaotunud, peaksid punktid Q-Q diagrammil paiknema ligikaudu sirgel joonel.
    \item
      \textbf{Formaalsed normaalsuse testid:} Näiteks Shapiro-Wilk test, Kolmogorov-Smirnov test, Jarque-Bera test. Need testid annavad statistilise p-väärtuse, mis hindab, kas jäägid erinevad oluliselt normaaljaotusest.
    \end{itemize}
  \item
    \textbf{Mis juhtub, kui eeldus on rikutud:} Väikeste valimite korral võivad t-testid ja F-testid olla ebausaldusväärsed. Suurte valimite korral on lineaarsed regressioonitulemused sageli robustsed normaalsuse rikkumise suhtes (tänu keskväärtusteoreemile).
  \item
    \textbf{Mida teha:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Muutujate transformeerimine:} Sõltuva muutuja transformeerimine võib mõnikord muuta jääkide jaotust normaalsemaks.
    \item
      \textbf{Mitteparameetrilised meetodid:} Kui normaalsuse rikkumine on tõsine ja valim on väike, võib kaaluda mitteparameetriliste regressioonimeetodite kasutamist, mis ei eelda normaaljaotust (kuid need meetodid võivad olla vähem võimsad kui lineaarne regressioon, kui eeldused on täidetud).
    \item
      \textbf{Suur valim:} Suurte valimite korral on lineaarne regressioon suhteliselt robustne normaalsuse rikkumise suhtes. Kui valim on piisavalt suur, ei pruugi normaalsuse eeldus olla nii kriitiline.
    \end{itemize}
  \end{itemize}
\item
  \textbf{Multikollineaarsuse puudumine:} Sõltumatud tunnused (argumenttunnused) ei tohiks omavahel tugevalt korreleeruda. Multikollineaarsus tekib siis, kui kaks või enam sõltumatut muutujat on omavahel tugevalt lineaarselt seotud.

  \begin{itemize}
  \tightlist
  \item
    \textbf{Mida see tähendab:} See tähendab, et sõltumatud muutujad ei tohiks olla üksteise ennustajad. Näiteks, kui me modelleerime palku haridustaseme ja töökogemuse põhjal, võib multikollineaarsus tekkida, kui haridustase ja töökogemus on tugevalt korreleeritud (kõrgema haridusega inimestel on tavaliselt rohkem töökogemust).
  \item
    \textbf{Miks see oluline on:} Multikollineaarsus ei mõjuta mudeli ennustusvõimet tervikuna, kuid see teeb üksikute sõltumatute muutujate mõju eristamise raskeks ja ebastabiilseks. Regressioonikoefitsiendid muutuvad ebatäpseks (suured standardvead) ja ebastabiilseks (väikesed muutused andmetes võivad põhjustada suuri muutusi koefitsientides). Samuti võib see muuta koefitsientide märke ootamatuks.
  \item
    \textbf{Kuidas kontrollida:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Korrelatsioonimaatriks:} Sõltumatute muutujate vahelise korrelatsioonimaatriksi arvutamine ja korrelatsioonikordajate (eriti Pearsoni korrelatsioonikordajate) vaatamine. Kõrged korrelatsioonikordajad (näiteks absoluutväärtus üle 0.7 või 0.8) võivad viidata multikollineaarsusele.
    \item
      \textbf{VIF (Variance Inflation Factor - dispersiooni paisutustegur):} VIF arvutatakse iga sõltumatu muutuja jaoks. See mõõdab, kui palju iga muutuja standardviga on paisunud multikollineaarsuse tõttu. Kõrged VIF väärtused (tavaliselt üle 5 või 10) viitavad multikollineaarsusele.
    \end{itemize}
  \item
    \textbf{Mis juhtub, kui eeldus on rikutud:} Regressioonikoefitsiendid on ebastabiilsed ja raskesti interpreteeritavad, standardvead paisuvad, mis teeb statistilised testid vähem võimsaks. Kuigi mudeli ennustusvõime tervikuna ei pruugi kannatada, on üksikute muutujate mõju raske hinnata.
  \item
    \textbf{Mida teha:}

    \begin{itemize}
    \tightlist
    \item
      \textbf{Muutujate eemaldamine:} Kui multikollineaarsus on probleemiks, võib eemaldada mudelist ühe või mitu omavahel korreleeruvat muutujat. Tuleb valida, millised muutujad on teoreetiliselt või praktiliselt vähem olulised või redundantsed.
    \item
      \textbf{Muutujate kombineerimine:} Korreleeritud muutujad võib kombineerida üheks uueks muutujaks (näiteks summeerida või arvutada keskmist).
    \item
      \textbf{PCA (Principal Component Analysis - peamiste komponentide analüüs) või PLS (Partial Least Squares - osalised vähimruudud) regressioon:} Need meetodid on spetsiifiliselt loodud multikollineaarsuse probleemi lahendamiseks. PCA regressioon teisendab algsed muutujad uuteks, ortogonaalseteks (mitte-korreleeritud) komponentideks ja kasutab neid regressioonis. PLS regressioon on eriti kasulik, kui on palju sõltumatuid muutujaid ja multikollineaarsus on tugev.
    \item
      \textbf{Regulariseerimine (näiteks Ridge regressioon või Lasso regressioon):} Regulariseerimise meetodid aitavad vähendada multikollineaarsuse mõju, ``kahandades'' koefitsiente ja vähendades nende dispersiooni (kuigi nad võivad ka koefitsientide hinnanguid ``biaseerida'').
    \end{itemize}
  \end{itemize}
\end{itemize}

\section{Lineaarne regressioon R-is}\label{lineaarne-regressioon-r-is}

\begin{naidis}
Proovitükil on mõõdetud puudel diameetrid ja kõrgused. Eesmärgiks on leida lineaarse regressiooniga mudel, millega ennustada diameetrist puude kõrgust.
\end{naidis}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Laadi alla \textquotesingle{}readxl\textquotesingle{} pakett, et lugeda Exceli faili}
\FunctionTok{library}\NormalTok{(readxl)}

\CommentTok{\# Loe andmed Exceli failist ja konkreetselt töölehelt}
\NormalTok{andmed }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/naited.xlsx"}\NormalTok{, }\AttributeTok{sheet =} \StringTok{"MA"}\NormalTok{)}

\CommentTok{\# Vaata, kuidas andmed välja näevad ja kontrolli veergude nimesid}
\FunctionTok{head}\NormalTok{(andmed)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 6 x 6
     NR     D     H    HV    VP   SHV
  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1    10   9.7  12.2   7.1   5.1  0.58
2    20  10.2  11.1   7.5   3.6  0.68
3    30   6.3   9.9   7     2.9  0.71
4    40   7.4  11     7.5   3.5  0.68
5    50   5.6   8.8   6.8   2    0.77
6    60   5.6  10.6   7.2   3.4  0.68
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lineaarse regressiooni mudeli loomine}
\CommentTok{\# Valem H = f(D) tähendab, et H on sõltuv muutuja ja D on sõltumatu muutuja.}
\CommentTok{\# R{-}is tähistatakse seda valemit kujul H \textasciitilde{} D}
\NormalTok{lm\_1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(H }\SpecialCharTok{\textasciitilde{}}\NormalTok{ D, }\AttributeTok{data =}\NormalTok{ andmed)}

\CommentTok{\# Mudeli kokkuvõtte kuvamine}
\FunctionTok{summary}\NormalTok{(lm\_1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = H ~ D, data = andmed)

Residuals:
    Min      1Q  Median      3Q     Max 
-2,1190 -0,6362 -0,0361  0,9079  1,9273 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)   5,6036     0,5427   10,32  1,0e-11
D             0,5481     0,0652    8,41  1,3e-09

Residual standard error: 1,15 on 32 degrees of freedom
Multiple R-squared:  0,688, Adjusted R-squared:  0,679 
F-statistic: 70,7 on 1 and 32 DF,  p-value: 1,32e-09
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\CommentTok{\# Joonista punktgraafik koos regressioonisirgega}
\FunctionTok{ggplot}\NormalTok{(andmed, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ D, }\AttributeTok{y =}\NormalTok{ H)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} \CommentTok{\# Lisa punktid andmete jaoks}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color=}\StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{xlim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{20}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{20}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-47-1} \caption{Hajuvusdiagramm}\label{fig:unnamed-chunk-47}
\end{figure}

\begin{naidis}
Täiendame regressioonimudelit, kus argumenttunnuseks on naturaallogaritm diameetrist.
\end{naidis}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lineaarse regressiooni mudeli loomine}
\CommentTok{\# R{-}is tähistatakse seda valemit kujul H \textasciitilde{} log(D)}
\FunctionTok{summary}\NormalTok{(lm\_2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(H }\SpecialCharTok{\textasciitilde{}} \FunctionTok{log}\NormalTok{(D), }\AttributeTok{data =}\NormalTok{ andmed))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = H ~ log(D), data = andmed)

Residuals:
   Min     1Q Median     3Q    Max 
-1,505 -0,532 -0,183  0,673  1,887 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)    0,871      0,799    1,09     0,28
log(D)         4,552      0,397   11,47  7,2e-13

Residual standard error: 0,909 on 32 degrees of freedom
Multiple R-squared:  0,804, Adjusted R-squared:  0,798 
F-statistic:  131 on 1 and 32 DF,  p-value: 7,2e-13
\end{verbatim}

Ning vaatame tulemust graafikul.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\CommentTok{\# Joonista punktgraafik koos regressioonisirgega}
\FunctionTok{ggplot}\NormalTok{(andmed, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ D, }\AttributeTok{y =}\NormalTok{ H)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} \CommentTok{\# Lisa punktid andmete jaoks}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{formula =}\NormalTok{ y}\SpecialCharTok{\textasciitilde{}}\FunctionTok{log}\NormalTok{(x),  }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color=}\StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{20}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{20}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-49-1} \caption{Hajuvusdiagramm logaritmilise teisendusega}\label{fig:unnamed-chunk-49}
\end{figure}

ANOVA (Analysis of Variance) on statistiline meetod, mida kasutatakse kahe või enama rühma keskmiste võrdlemiseks. Regressioonimudelite puhul saab ANOVA-t kasutada kahe mudeli võrdlemiseks, et näha, kas üks mudel selgitab oluliselt rohkem varieeruvust kui teine mudel.

\textbf{Eeldused}

Enne ANOVA kasutamist on oluline tagada, et andmed vastavad järgmistele eeldustele:

\begin{itemize}
\tightlist
\item
  Sõltuv tunnus peab olema pidev.
\item
  Sõltumatud tunnused võivad olla nii pidevad kui ka kategoorilised.
\item
  Vigade dispersioon peab olema konstantne (homoskedastsus).
\item
  Vead peavad olema normaalselt jaotunud.
\item
  Vaatlused peavad olema sõltumatud.
\end{itemize}

\textbf{ANOVA läbiviimine}

Antud juhul on meil kaks mudelit:

\begin{itemize}
\tightlist
\item
  \textbf{Mudel 1.} \texttt{H\textasciitilde{}D}
\item
  \textbf{Mudel 2.} \texttt{H\textasciitilde{}log(D)}
\end{itemize}

ANOVA abil saame võrrelda neid kahte mudelit, et näha, kas mudel 2 selgitab oluliselt rohkem varieeruvust kui mudel 1.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(aov\_1 }\OtherTok{\textless{}{-}} \FunctionTok{anova}\NormalTok{(lm\_1, lm\_2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Analysis of Variance Table

Model 1: H ~ D
Model 2: H ~ log(D)
  Res.Df  RSS Df Sum of Sq F Pr(>F)
1     32 42,1                      
2     32 26,5  0      15,7         
\end{verbatim}

Tulemusest näeme, et esimese mudeli hälvete ruutude summa (RSS) on suurem (\text{42,1308} \textgreater{} \text{26,46116}), seega on teine mudel täpsem.

\begin{naidis}
Hindame mudelite jääkide jaotust ning hindame, kas need vastavad normaaljaotusele.
\end{naidis}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{mgp=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\FloatTok{0.7}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(}\FunctionTok{resid}\NormalTok{(lm\_1), }\AttributeTok{bw =} \FloatTok{0.5}\NormalTok{), }\AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.4}\NormalTok{), }\AttributeTok{main=}\StringTok{""}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Jäägid"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"f(x)"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(}\FunctionTok{density}\NormalTok{(}\FunctionTok{resid}\NormalTok{(lm\_2), }\AttributeTok{bw =} \FloatTok{0.5}\NormalTok{), }\AttributeTok{col =} \DecValTok{2}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-51-1} \caption{Lineaarse regressiooni jääkide tihedusfunktsioon.}\label{fig:unnamed-chunk-51}
\end{figure}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(sh\_tst\_1 }\OtherTok{\textless{}{-}} \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{resid}\NormalTok{(lm\_1)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    Shapiro-Wilk normality test

data:  resid(lm_1)
W = 0,957, p-value = 0,2
\end{verbatim}

Sinu antud tulemus näitab järgmist:

\begin{itemize}
\tightlist
\item
  \textbf{W = \text{0,95708}:} See on teststatistik. W väärtus, mis on lähedal 1-le, viitab sellele, et andmed on tõenäoliselt normaaljaotusega.
\item
  \textbf{p-value = \text{0,19958}:} See on olulisuse tõenäosus (p-väärtus). See näitab tõenäosust, et saaksid sarnase või ekstreemsema tulemuse, kui andmed tegelikult oleksid normaaljaotusega.
\end{itemize}

\textbf{Järeldus}

Kuna p-väärtus (\text{0,95708}) on suurem kui tavaline \(\alpha\)-tase 0,05, siis me ei saa nullhüpoteesi (et andmed on normaaljaotusega) ümber lükata. See tähendab, et antud andmete põhjal \textbf{ei ole piisavalt tõendeid selle kohta, et andmed ei oleks normaaljaotusega}.

\textbf{Täiendavad kaalutlused}

\begin{itemize}
\tightlist
\item
  \textbf{Praktiline olulisus:} Kuigi test näitab, et andmed ei pruugi olla \emph{täpselt} normaaljaotusega, võib see kõrvalekalle olla piisavalt väike, et mitte mõjutada oluliselt järgnevaid statistilisi analüüse.
\item
  \textbf{Visuaalne kontroll:} Lisaks testile on alati kasulik andmeid visuaalselt kontrollida näiteks histogrammi või Q-Q graafiku abil. See aitab paremini mõista andmete jaotust ja võimalikke kõrvalekaldeid.
\end{itemize}

\textbf{Kokkuvõtteks:} Shapiro-Wilki testi tulemus näitab, et andmed on tõenäoliselt normaaljaotusega, kuid alati on hea mõelda ka andmete praktilisele olulisusele ja neid visuaalselt kontrollida.

\section{Lineaarne regressioon mitme tunnusega}\label{lineaarne-regressioon-mitme-tunnusega}

\begin{naidis}
Koostame mitmese lineaarse regressiooni, kus võraalguse kõrgus ennustatakse diameetri ja kõrgus alusel (HV = D + H).
\end{naidis}

Koostame mudeli, mille valem on \texttt{HV\textasciitilde{}D+H}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(lm\_3 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(HV}\SpecialCharTok{\textasciitilde{}}\NormalTok{D}\SpecialCharTok{+}\NormalTok{H, andmed))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = HV ~ D + H, data = andmed)

Residuals:
    Min      1Q  Median      3Q     Max 
-1,2054 -0,4429  0,0429  0,4105  1,4123 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)   1,1089     0,6170    1,80    0,082
D            -0,3601     0,0638   -5,65  3,4e-06
H             0,7795     0,0966    8,07  4,1e-09

Residual standard error: 0,627 on 31 degrees of freedom
Multiple R-squared:  0,689, Adjusted R-squared:  0,669 
F-statistic: 34,3 on 2 and 31 DF,  p-value: 1,37e-08
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(lm\_3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Analysis of Variance Table

Response: HV
          Df Sum Sq Mean Sq F value  Pr(>F)
D          1   1,39    1,39    3,55   0,069
H          1  25,60   25,60   65,15 4,1e-09
Residuals 31  12,18    0,39                
\end{verbatim}

Mudeli ANOVA test näitab, et diameetri mõju ei pruugi olla oluline.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Koostame täiendava mudeli, mis sõltub ainult kõrgusest}
\NormalTok{lm\_4 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(HV}\SpecialCharTok{\textasciitilde{}}\NormalTok{H, andmed)}
\CommentTok{\# Võrdleme kahte mudelit omavahel}
\NormalTok{aov\_2 }\OtherTok{\textless{}{-}} \FunctionTok{anova}\NormalTok{(lm\_4, lm\_3)}
\end{Highlighting}
\end{Shaded}

Tulemusest on näha, et täiendavalt diameetrit sisaldav mudel on oluliselt (p-väärtus \text{\ensuremath{3,37587\times 10^{-6}}}) täpsem, kui ainult kõrgusest sõltuv mudel.

Kasutame funktsiooni \texttt{termplot()}, et hinnata regressioonimudeli üksikute terminite mõju visualselt. See aitab mõista, kuidas iga argumenttunnus mõjutab funktsioontunnust, kui kõik teised tunnused hoitakse konstantsena.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Regressioonimudel:} Esiteks pead looma regressioonimudeli (lineaarne, üldistatud lineaarne või mõni muu), kasutades näiteks funktsioone nagu \texttt{lm} või \texttt{glm}.
\item
  \textbf{\texttt{termplot()} funktsioon:} Seejärel kasutad funktsiooni \texttt{termplot}, andes sellele mudeli ja määrates, milliseid termineid (tunnuseid) soovid visualiseerida.
\item
  \textbf{Graafik:} \texttt{termplot} loob graafiku, kus x-teljel on konkreetse tunnuse väärtused ja y-teljel on selle tunnuse mõju vastussuurusele. Graafik näitab, kuidas vastussuurus muutub, kui tunnuse väärtus muutub, hoides samal ajal kõik teised tunnused konstantsena.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfcol=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{), }\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{mgp=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\FloatTok{0.7}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\FunctionTok{termplot}\NormalTok{(lm\_3, }\AttributeTok{partial.resid =}\NormalTok{ T, }\AttributeTok{se=}\NormalTok{T)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-56-1} \caption{Argumenttunnuste mõju funktsioontunnusele.}\label{fig:unnamed-chunk-56}
\end{figure}

\textbf{Olulised parameetrid}

\begin{itemize}
\tightlist
\item
  \textbf{\texttt{model}:} Regressioonimudel, mille jaoks termplot luuakse.
\item
  \textbf{\texttt{terms}:} Vektor, mis määrab, milliseid termineid (tunnuseid) soovitakse visualiseerida.
\item
  \textbf{\texttt{partial.resid}:} Loogiline väärtus, mis määrab, kas graafikule lisatakse osalised jäägid.
\item
  \textbf{\texttt{se}:} Loogiline väärtus, mis määrab, kas graafikule lisatakse standardvead.
\end{itemize}

Vaatame tunnuste omavahelist korrelatsiooni ning sellest näeme, et D ja H vahel on tugev korrelatsioon. See mõjutab ka mudeli parameetreid.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(andmed[,}\FunctionTok{c}\NormalTok{(}\StringTok{"D"}\NormalTok{,}\StringTok{"H"}\NormalTok{, }\StringTok{"HV"}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
         D       H      HV
D  1,00000 0,82967 0,18860
H  0,82967 1,00000 0,60777
HV 0,18860 0,60777 1,00000
\end{verbatim}

\chapter{Mittelineaarne regressioon}\label{mittelineaarne-regressioon}

\textbf{Mittelineaarne regressioon} on statistiline meetod, mida kasutatakse sõltuva muutuja ja ühe või mitme sõltumatu muutuja vahelise mittelineaarse seose modelleerimiseks. Erinevalt lineaarsest regressioonist, mis eeldab sirgjoonelist seost, võimaldab mittelineaarne regressioon paindlikumaid seoseid, näiteks kõverjoonelisi, eksponentsiaalseid või logistilisi seoseid.

Metsanduses esineb sageli mittelineaarseid seoseid. Mittelineaarne regressioon võimaldab neid keerukaid seoseid täpsemalt modelleerida ja paremini mõista.

Mittelineaarne regressioonimudel kirjutatakse üldjuhul kujul:

\[Y = f(X, \beta) + \epsilon\]

kus:

\begin{itemize}
\tightlist
\item
  \textbf{Y} on sõltuv muutuja.
\item
  \textbf{X} on sõltumatu(te) muutuja(te) vektor.
\item
  \textbf{\(f(X, \beta)\)} on mittelineaarne funktsioon, mis kirjeldab seost X ja Y vahel.
\item
  \textbf{\(\beta\)} on mudeli parameetrite vektor, mida tuleb hinnata.
\item
  \textbf{\(\epsilon\)} on vealiige, mis esindab juhuslikku varieeruvust.
\end{itemize}

Mittelineaarse regressiooni parameetreid hinnatakse tavaliselt \textbf{vähimruutude meetodil}, kus otsitakse parameetrite väärtusi, mis minimeerivad mudeli ennustatud väärtuste ja tegelike väärtuste vaheliste ruutude summat. See on iteratiivne protsess, mis nõuab arvutitarkvara kasutamist.

\section{Mittelineaarne regressioon R keskkonnas}\label{mittelineaarne-regressioon-r-keskkonnas}

R-is kasutatakse mittelineaarse regressiooni lähendamiseks funktsiooni \texttt{nls()}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Laadime peatükis kasutatavad paketid}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{naidis}
Olgu meil ülesandeks lähendada Eesti riigimetsa pohla kasvukohatüübi männikute keskmiste kõrguste vanuserea andmed Mitcherlichi kasvufunktsiooniga
\end{naidis}

\[H = c0 * (1 - exp(-c1 * A))^{c2}\]

Kus A on vanus, H on puistu kõrgus ning c0, c1 ja c2 on mudeli parameetrid.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Laadime andmed sisse failist ning}
\CommentTok{\# filtreerime välja puud, mille h \textgreater{} 0}
\NormalTok{andmed }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/naited.xlsx"}\NormalTok{,}\StringTok{"PH\_MA"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Mudeli lähendamiseks koostame esmalt oma funktsiooni ning lisame täiendava teisenduse, kus vanus jagatakse 100-ga. Kuna parameeter \(c_1\) korrutatakse valemis vanusega ning selle parameetri väärtus on väga väike, siis lähendamine on lihtsam, kui see on sada korda suurem ehk 0,02 asemel on 2.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Määratleme mudeli funktsioon}
\NormalTok{kasvuMudel }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(A, c0, c1, c2) \{}
\NormalTok{ c0 }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{c1 }\SpecialCharTok{*}\NormalTok{ A}\SpecialCharTok{/}\DecValTok{100}\NormalTok{))}\SpecialCharTok{\^{}}\NormalTok{c2}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Omistame algväärtused parameetritele}
\NormalTok{alg\_param }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\AttributeTok{c0 =} \DecValTok{20}\NormalTok{, }\AttributeTok{c1 =} \DecValTok{2}\NormalTok{, }\AttributeTok{c2 =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Sobitame mudel andmetele}
\NormalTok{mudel }\OtherTok{\textless{}{-}} \FunctionTok{nls}\NormalTok{(H }\SpecialCharTok{\textasciitilde{}} \FunctionTok{kasvuMudel}\NormalTok{(A, c0, c1, c2), }\AttributeTok{data =}\NormalTok{ andmed, }\AttributeTok{start =}\NormalTok{ alg\_param)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Vaatame mudeli kokkuvõtet}
\FunctionTok{summary}\NormalTok{(mudel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Formula: H ~ kasvuMudel(A, c0, c1, c2)

Parameters:
   Estimate Std. Error t value Pr(>|t|)
c0  26,8400     0,2211   121,4  < 2e-16
c1   2,2104     0,0787    28,1  1,4e-11
c2   1,4858     0,0510    29,1  9,2e-12

Residual standard error: 0,175 on 11 degrees of freedom

Number of iterations to convergence: 4 
Achieved convergence tolerance: 1,52e-06
\end{verbatim}

Esitame selle kohta ka graafiku kasutades funktsiooni \texttt{ggplot()}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(andmed, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ A, }\AttributeTok{y =}\NormalTok{ H)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{stat\_function}\NormalTok{(}
    \AttributeTok{fun =} \ControlFlowTok{function}\NormalTok{(x)}
      \FunctionTok{predict}\NormalTok{(mudel, }\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{A =}\NormalTok{ x)),}
    \AttributeTok{color =} \DecValTok{2}
\NormalTok{  ) }
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-65-1} \caption{Mittelineaarne regressioon}\label{fig:unnamed-chunk-65}
\end{figure}

Testime mittelineaarset lähenemist puu diameetri ja kõrguse vahelise seose modelleerimiseks.

Kasutame samu andmeid nagu lineaarses regressioonis.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Loe andmed Exceli failist ja konkreetselt töölehelt}
\NormalTok{prt }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/naited.xlsx"}\NormalTok{, }\AttributeTok{sheet =} \StringTok{"MA"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lühendame koodi ning kirjutame ühe käsuna}
\FunctionTok{summary}\NormalTok{(nls\_mudel }\OtherTok{\textless{}{-}} \FunctionTok{nls}\NormalTok{(H }\SpecialCharTok{\textasciitilde{}} \FloatTok{1.3} \SpecialCharTok{+}\NormalTok{ (D }\SpecialCharTok{/}\NormalTok{ (c0 }\SpecialCharTok{+}\NormalTok{ c1 }\SpecialCharTok{*}\NormalTok{ D))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{, prt, }\AttributeTok{start =} \FunctionTok{list}\NormalTok{(}\AttributeTok{c0 =} \DecValTok{1}\NormalTok{, }\AttributeTok{c1 =} \DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Formula: H ~ 1.3 + (D/(c0 + c1 * D))^2

Parameters:
   Estimate Std. Error t value Pr(>|t|)
c0  0,66193    0,06532    10,1  1,6e-11
c1  0,24866    0,00832    29,9  < 2e-16

Residual standard error: 0,883 on 32 degrees of freedom

Number of iterations to convergence: 8 
Achieved convergence tolerance: 1,03e-06
\end{verbatim}

Järgnevalt kontrollime ka jääkide hajuvust.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{fitted =} \FunctionTok{fitted}\NormalTok{(nls\_mudel), }\AttributeTok{resid =} \FunctionTok{resid}\NormalTok{(nls\_mudel)),}
       \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ fitted, }\AttributeTok{y =}\NormalTok{ resid)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"gam"}\NormalTok{, }\AttributeTok{formula =}\NormalTok{ y }\SpecialCharTok{\textasciitilde{}} \FunctionTok{s}\NormalTok{(x))  }\CommentTok{\# Lisab sujuva joone GAM mudeli abil}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-68-1} \caption{Jäägid vs ennustatud}\label{fig:unnamed-chunk-68}
\end{figure}

\textbf{Mida sellelt graafikult otsida:}

\begin{itemize}
\tightlist
\item
  \textbf{Juhuslik hajuvus:} Ideaalis peaksid punktid paiknema juhuslikult nulljoone ümber, ilma selge mustrita.
\item
  \textbf{Süsteemne muster:} Kui punktid moodustavad mingi süsteemse mustri (nt kaar, lehter), siis see viitab probleemidele mudelis (nt mittelineaarsus, heteroskedastiivsus).
\item
  \textbf{Silutud joone kuju:} Kui silutud joon on sirge ja horisontaalne, siis see viitab, et ennustatud väärtuste ja jääkide vahel puudub süsteemne seos. Kui joon on kõver, siis see viitab mittelineaarsele seosele, mida mudel ei pruugi arvesse võtta.
\end{itemize}

\section{Mittelineaarne regressioon MS Excel keskkonnas}\label{mittelineaarne-regressioon-ms-excel-keskkonnas}

MS Exceli keskkonnas saab mittelineaarse funktsiooni parameetrite hindamiseks kasutada optimeerimisprotseduuri Solver. Selleks tuleks MS Exceli töölehele salvestada argumenttunnuse väärtused, funktsioontunnuse väärtused, prognoosifunktsiooni arvutusvalemid ja prognoosijääkide ruutude summa arvutuseeskiri. Samuti peavad töölehel olema lahtrid funktsiooni parameetrite jaoks, mida prognoosifunktsiooni arvutusvalemid kasutavad. MS Exceli optimeerimisalgoritm käivitatakse menüüst: Andmed, Solver.

Andmete ettevalmistamisel tuleb esmalt määrata lahtrid, kuhu kirjutatakse mudeli parameetrid. Järgnevas näites on need lahtrites G1:G3 ning nende nimetused on lahtrites F1:F3. Kõrguse kõrval tulpa on sisestatud valem, millega kõrgust prognoositakse sõltuvalt vanusest. Eraldi on välja arvutatud prognoosijääkide ruutude summa (SSE) MS Exceli funktsiooniga \texttt{SUMXMY2()}, millel on sisendiks tegelik kõrgus ja prognoositud kõrgus.

Solverile tuleb anda ette lahtrid, mille väärtust minimeeritakse (SSE) ja lahtrid, mille väärtusi protseduur hakkab muutma, et minimeerida prognoosijääkide ruutude summat.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{pildid/ms_excel_solver.png}}
\caption{Solveriga parameetrite lähendamine}
\end{figure}

\chapter{Mitteparameetriline analüüs}\label{mitteparameetriline-analuxfcuxfcs}

\section{Üldistatud aditiivne mudel}\label{uxfcldistatud-aditiivne-mudel}

Üldistatud aditiivne mudel (GAM) on statistiline mudel, mis ühendab lineaarse mudeli omadused aditiivsete funktsioonide abil. Lihtsamalt öeldes on GAM mudel, mis modelleerib funktsioontunnust ühe või mitme argumenttunnuse summa abil, kus iga argumenttunnuse mõju funktsioontunnusele modelleeritakse splainfunktsiooni abil.

Splainfunktsioon on matemaatiline funktsioon, mida kasutatakse andmete interpoleerimiseks ja sujuvaks lähendamiseks. See on ühesuguse struktuuriga tükiti polünomiaalne funktsioon, mis on konstrueeritud nii, et see oleks sujuv ja pidev andmepunktide vahel. See tähendab, et splainfunktsioonil ei ole järske hüppeid ega nurki, mis teeb selle ideaalseks tööriistaks sujuvate kõverate ja pindade modelleerimiseks.

Selles näites kasutame R-i paketti \texttt{mgcv} GAM mudeli sobitamiseks. Eesmärk on modelleerida puu kõrguse ja diameetri vahelist seost, eeldades, et see seos ei pruugi olla lineaarne.

Kõigepealt laadime andmestiku, mis sisaldab puude kõrguse ja diameetri mõõtmiste andmeid.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Laadime peatükis kasutatavad paketid}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(mgcv)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Andmete laadimine}
\NormalTok{andmed }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/naited.xlsx"}\NormalTok{,}\StringTok{"prt\_andmed"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(h }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

GAM mudeli lähendamiseks kasutame funktsiooni \texttt{gam()} paketist \texttt{mgcv}. Kasutame splainfunktsiooni diameetri muutuja jaoks, et modelleerida mittelineaarset seost.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# GAM mudeli sobitamine}
\NormalTok{mudel }\OtherTok{\textless{}{-}} \FunctionTok{gam}\NormalTok{(h }\SpecialCharTok{\textasciitilde{}} \FunctionTok{s}\NormalTok{(d), }\AttributeTok{data =}\NormalTok{ andmed)}
\end{Highlighting}
\end{Shaded}

Selles koodis:

\begin{itemize}
\tightlist
\item
  \texttt{H\ \textasciitilde{}\ s(D)} määrab mudeli valemi. \texttt{H} on funktsioontunnus ja \texttt{s(D)} määrab, et diameetri (D) mõju kõrgusele modelleeritakse sujuva funktsiooni \texttt{s()} abil.
\item
  \texttt{data\ =\ andmed} määrab andmestiku, mida kasutada.
\end{itemize}

\textbf{3. Mudeli kokkuvõtte vaatamine:}

Saame mudeli kohta detailse kokkuvõtte funktsiooni \texttt{summary()} abil:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mudeli kokkuvõte}
\FunctionTok{summary}\NormalTok{(mudel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Family: gaussian 
Link function: identity 

Formula:
h ~ s(d)

Parametric coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)   24,368      0,182     134   <2e-16

Approximate significance of smooth terms:
      edf Ref.df  F p-value
s(d) 3,68   4,61 24  <2e-16

R-sq.(adj) =  0,705   Deviance explained = 72,8%
GCV = 1,7242  Scale est. = 1,5525    n = 47
\end{verbatim}

Kokkuvõte annab meile informatsiooni mudeli sobivuse kohta, sh:

\begin{itemize}
\tightlist
\item
  \textbf{Parametric coefficients:} Kui mudelis on ka lineaarseid komponente, näidatakse siin nende koefitsiendid. Kuna mudelis ühtegi lineaarset tunnust ei ole kasutatud, siis on siin ainult vabaliige \texttt{(Intercept)}.
\item
  \textbf{Approximate significance of smooth terms:} Siin näeme p-väärtuse hinnangut splainfunktsiooni olulisuse kohta. Madal p-väärtus (\textless0.05) viitab statistiliselt olulisele mittelineaarsele seosele diameetri ja kõrguse vahel.
\item
  \textbf{R-sq.(adj):} Korrigeeritud determinatsioonikordaja näitab, kui suure osa kõrguse varieeruvusest mudel seletab.
\item
  \textbf{Deviance explained:} Sarnane determinatsioonikordajale, näitab mudeli poolt seletatud hälbimuse osakaalu.
\end{itemize}

Kasutades funktsiooni \texttt{coef()}, näeme splainfunktsiooni polünoomi parameetrite väärtusi.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(mudel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
(Intercept)      s(d).1      s(d).2      s(d).3      s(d).4      s(d).5 
 24,3680851  -1,6514056  -0,8997401  -0,0019625   0,0345575  -0,0430375 
     s(d).6      s(d).7      s(d).8      s(d).9 
  0,1877321  -0,1323456  -0,8129444   3,4477405 
\end{verbatim}

Saame visualiseerida diameetri ja kõrguse vahelist seost funktsiooni \texttt{plot()} abil:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mudeli visualiseerimine}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{mgp=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\FloatTok{0.7}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(mudel)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-75-1} \caption{Kõrguse sõltuvus diameetrist}\label{fig:unnamed-chunk-75}
\end{figure}

See kuvab graafiku, mis näitab diameetri mõju puu kõrgusele. Pidevjoon näitab modelleeritud seost ja kriipsjooned näitavad usaldusvahemikku. See graafik aitab visuaalselt hinnata seose kuju ja mittelineaarsust.

Saame kasutada mudelit uute puude kõrguse ennustamiseks, andes ette diameetri väärtused funktsiooni \texttt{predict()} abil:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Uute diameetrite väärtused}
\NormalTok{uued\_andmed }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{d =} \FunctionTok{c}\NormalTok{(}\DecValTok{12}\NormalTok{, }\DecValTok{22}\NormalTok{, }\DecValTok{32}\NormalTok{))}

\CommentTok{\# Ennustuste tegemine}
\NormalTok{uued\_andmed}\SpecialCharTok{$}\NormalTok{h }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(mudel, }\AttributeTok{newdata =}\NormalTok{ uued\_andmed)}

\CommentTok{\# Ennustuste kuvamine}
\FunctionTok{print}\NormalTok{(uued\_andmed)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   d      h
1 12 18,134
2 22 24,092
3 32 26,298
\end{verbatim}

\section{\texorpdfstring{Visualiseerimine paketiga \texttt{ggplot2}}{Visualiseerimine paketiga ggplot2}}\label{visualiseerimine-paketiga-ggplot2}

Oletame, et meil on samad andmed puude kõrguse (h) ja diameetri (d) kohta nagu eelmistes näidetes, aga me tahame luua hajuvusdiagrammi ja lisada sellele sujuva joone otse \texttt{ggplot2} abil, ilma et peaks eraldi \texttt{gam()} funktsiooni kasutama.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Laadi pakett}
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

Kasutame \texttt{ggplot()} funktsiooni koos \texttt{geom\_point()} ja \texttt{geom\_smooth()} funktsioonidega:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(andmed, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ d, }\AttributeTok{y =}\NormalTok{ h)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}  \CommentTok{\# Joonistab hajuvusdiagrammi}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"gam"}\NormalTok{, }\AttributeTok{formula =}\NormalTok{ y }\SpecialCharTok{\textasciitilde{}} \FunctionTok{s}\NormalTok{(x)) }\SpecialCharTok{+}  \CommentTok{\# Lisab sujuva joone GAM mudeli abil}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Diameeter (cm)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Kõrgus (m)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-78-1} \caption{Kõrguse sõltuvus diameetrist}\label{fig:unnamed-chunk-78}
\end{figure}

Selgitus:

\begin{itemize}
\tightlist
\item
  \texttt{ggplot(puud,\ aes(x\ =\ d,\ y\ =\ h))}: See rida loob \texttt{ggplot} objekti ja määrab andmestiku (\texttt{andmed}) ning x-telje (diameeter - \texttt{D}) ja y-telje (kõrgus - \texttt{H}) muutujad.
\item
  \texttt{geom\_point()}: See funktsioon lisab graafikule punktid, luues hajuvusdiagrammi. Iga punkt esindab ühte puud.
\item
  \texttt{geom\_smooth(method\ =\ "gam",\ formula\ =\ y\ \textasciitilde{}\ s(x))}: See funktsioon lisab graafikule sujuva joone.

  \begin{itemize}
  \tightlist
  \item
    \texttt{method\ =\ "gam"}: Määrab, et sujuva joone sobitamiseks kasutatakse GAM mudelit.
  \item
    \texttt{formula\ =\ y\ \textasciitilde{}\ s(x)}: Määrab mudeli valemi. \texttt{y\ \textasciitilde{}\ s(x)} tähendab, et \texttt{y} (meie puhul kõrgus \texttt{H}) modelleeritakse \texttt{x} (meie puhul diameeter \texttt{D}) sujuva funktsiooni \texttt{s()} abil. See on sama valem, mida kasutasime eelmistes näidetes \texttt{gam()} funktsiooni sees.
  \end{itemize}
\item
  \texttt{labs(...)}: Määrab telgede sildid ja graafiku pealkirja.
\item
  \texttt{theme\_bw()}: Muudab graafiku teema must-valgeks.
\end{itemize}

Sarnaselt eelmisele näitele saate \texttt{ggplot2} abil graafikut vastavalt oma soovile kohandada. Näiteks:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(andmed, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ d, }\AttributeTok{y =}\NormalTok{ h, }\AttributeTok{color =}\NormalTok{ pl)) }\SpecialCharTok{+}
  \CommentTok{\# Muudab punktide värvi, kuju ja suurust}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}  
  \CommentTok{\# Eemaldab usaldusvahemiku ja muudab joone värvi}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"gam"}\NormalTok{, }\AttributeTok{formula =}\NormalTok{ y }\SpecialCharTok{\textasciitilde{}} \FunctionTok{s}\NormalTok{(x)) }\SpecialCharTok{+}  
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Diameeter (D)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Kõrgus (H)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/unnamed-chunk-79-1} \caption{Kõrguse sõltuvus diameetrist}\label{fig:unnamed-chunk-79}
\end{figure}

Selles näites:

\begin{itemize}
\tightlist
\item
  \texttt{aes(x\ =\ D,\ y\ =\ H,\ color\ =\ PL)} on lisatud, et värv sõltub puuliigist.
\end{itemize}

See näide demonstreerib, kuidas luua hajuvusdiagramm ja lisada sellele sujuv joon, mis on sobitatud GAM mudeli abil, kasutades ainult \texttt{ggplot2} funktsioone. See on mugav viis kiiresti visualiseerida mittelineaarseid seoseid andmetes ilma eraldi GAM mudelit sobitamata. \texttt{ggplot2} pakub laialdasi võimalusi graafikute kohandamiseks, võimaldades luua informatiivseid ja visuaalselt meeldivaid visualiseeringuid.

\bibliography{book.bib,packages.bib}

\end{document}
